//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: Simulator.ice
//  Source: Simulator.idsl
//
//******************************************************************
#ifndef ROBOCOMPSIMULATOR_ICE
#define ROBOCOMPSIMULATOR_ICE
module RoboCompSimulator
{
	interface Simulator
	{
		void regenerate (string scene);
	};
};

#endif
