// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `ByteSequencePublisher.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <ByteSequencePublisher.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ids[2] =
{
    "::Ice::Object",
    "::RoboCompByteSequencePublisher::ByteSequencePublisher"
};
const ::std::string iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newsequence"
};
const ::std::string iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_newsequence_name = "newsequence";

}

bool
RoboCompByteSequencePublisher::ByteSequencePublisher::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ids, iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ids + 2, s);
}

::std::vector<::std::string>
RoboCompByteSequencePublisher::ByteSequencePublisher::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ids[0], &iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ids[2]);
}

::std::string
RoboCompByteSequencePublisher::ByteSequencePublisher::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompByteSequencePublisher::ByteSequencePublisher::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompByteSequencePublisher::ByteSequencePublisher";
    return typeId;
}

bool
RoboCompByteSequencePublisher::ByteSequencePublisher::_iceD_newsequence(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompByteSequencePublisher::bytesequence iceP_bs;
    istr->readAll(iceP_bs);
    inS.endReadParams();
    this->newsequence(::std::move(iceP_bs), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompByteSequencePublisher::ByteSequencePublisher::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ops, iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_newsequence(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompByteSequencePublisher::ByteSequencePublisherPrx::_iceI_newsequence(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompByteSequencePublisher::bytesequence& iceP_bs, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_newsequence_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_bs);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
RoboCompByteSequencePublisher::ByteSequencePublisherPrx::_newInstance() const
{
    return ::IceInternal::createProxy<ByteSequencePublisherPrx>();
}

const ::std::string&
RoboCompByteSequencePublisher::ByteSequencePublisherPrx::ice_staticId()
{
    return RoboCompByteSequencePublisher::ByteSequencePublisher::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_newsequence_name = "newsequence";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompByteSequencePublisher::upCast(::IceProxy::RoboCompByteSequencePublisher::ByteSequencePublisher* p) { return p; }

void
::IceProxy::RoboCompByteSequencePublisher::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompByteSequencePublisher::ByteSequencePublisher>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompByteSequencePublisher::ByteSequencePublisher;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompByteSequencePublisher::ByteSequencePublisher::_iceI_begin_newsequence(const ::RoboCompByteSequencePublisher::bytesequence& iceP_bs, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_newsequence_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_newsequence_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_bs);
        result->endWriteParams();
        result->invoke(iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_newsequence_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompByteSequencePublisher::ByteSequencePublisher::end_newsequence(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_newsequence_name);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompByteSequencePublisher::ByteSequencePublisher::_newInstance() const
{
    return new ByteSequencePublisher;
}

const ::std::string&
IceProxy::RoboCompByteSequencePublisher::ByteSequencePublisher::ice_staticId()
{
    return ::RoboCompByteSequencePublisher::ByteSequencePublisher::ice_staticId();
}

RoboCompByteSequencePublisher::ByteSequencePublisher::~ByteSequencePublisher()
{
}

::Ice::Object* RoboCompByteSequencePublisher::upCast(::RoboCompByteSequencePublisher::ByteSequencePublisher* p) { return p; }


namespace
{
const ::std::string iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ids[2] =
{
    "::Ice::Object",
    "::RoboCompByteSequencePublisher::ByteSequencePublisher"
};

}

bool
RoboCompByteSequencePublisher::ByteSequencePublisher::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ids, iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompByteSequencePublisher::ByteSequencePublisher::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ids[0], &iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ids[2]);
}

const ::std::string&
RoboCompByteSequencePublisher::ByteSequencePublisher::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompByteSequencePublisher::ByteSequencePublisher::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompByteSequencePublisher::ByteSequencePublisher";
    return typeId;
#else
    return iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_ids[1];
#endif
}

bool
RoboCompByteSequencePublisher::ByteSequencePublisher::_iceD_newsequence(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompByteSequencePublisher::bytesequence iceP_bs;
    istr->read(iceP_bs);
    inS.endReadParams();
    this->newsequence(iceP_bs, current);
    inS.writeEmptyParams();
    return true;
}

namespace
{
const ::std::string iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newsequence"
};

}

bool
RoboCompByteSequencePublisher::ByteSequencePublisher::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_all, iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompByteSequencePublisher_ByteSequencePublisher_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_newsequence(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompByteSequencePublisher::ByteSequencePublisher::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::RoboCompByteSequencePublisher::ByteSequencePublisher, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompByteSequencePublisher::ByteSequencePublisher::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::RoboCompByteSequencePublisher::ByteSequencePublisher, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
RoboCompByteSequencePublisher::_icePatchObjectPtr(ByteSequencePublisherPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompByteSequencePublisher::ByteSequencePublisherPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompByteSequencePublisher::ByteSequencePublisher::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
