// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `CommonBehavior.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __CommonBehavior_h__
#define __CommonBehavior_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompCommonBehavior
{

class CommonBehavior;
class CommonBehaviorPrx;

}

namespace RoboCompCommonBehavior
{

enum class State : unsigned char
{
    Starting,
    Running
};

struct Parameter
{
    bool editable;
    ::std::string value;
    ::std::string type;

    std::tuple<const bool&, const ::std::string&, const ::std::string&> ice_tuple() const
    {
        return std::tie(editable, value, type);
    }
};

using ParameterList = ::std::map<::std::string, ::RoboCompCommonBehavior::Parameter>;

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace RoboCompCommonBehavior
{

class CommonBehavior : public virtual ::Ice::Object
{
public:

    using ProxyType = CommonBehaviorPrx;

    virtual bool ice_isA(::std::string, const ::Ice::Current&) const override;
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current&) const override;
    virtual ::std::string ice_id(const ::Ice::Current&) const override;

    static const ::std::string& ice_staticId();

    virtual ::RoboCompCommonBehavior::ParameterList getParameterList(const ::Ice::Current&) = 0;
    bool _iceD_getParameterList(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual int getPeriod(const ::Ice::Current&) = 0;
    bool _iceD_getPeriod(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::RoboCompCommonBehavior::State getState(const ::Ice::Current&) = 0;
    bool _iceD_getState(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void killYourSelf(const ::Ice::Current&) = 0;
    bool _iceD_killYourSelf(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void reloadConfig(const ::Ice::Current&) = 0;
    bool _iceD_reloadConfig(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setParameterList(::RoboCompCommonBehavior::ParameterList, const ::Ice::Current&) = 0;
    bool _iceD_setParameterList(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setPeriod(int, const ::Ice::Current&) = 0;
    bool _iceD_setPeriod(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual int timeAwake(const ::Ice::Current&) = 0;
    bool _iceD_timeAwake(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
};

}

namespace RoboCompCommonBehavior
{

class CommonBehaviorPrx : public virtual ::Ice::Proxy<CommonBehaviorPrx, ::Ice::ObjectPrx>
{
public:

    ::RoboCompCommonBehavior::ParameterList getParameterList(const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::RoboCompCommonBehavior::ParameterList>(true, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_getParameterList, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getParameterListAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompCommonBehavior::ParameterList>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompCommonBehavior::ParameterList, P>(false, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_getParameterList, context);
    }

    ::std::function<void()>
    getParameterListAsync(::std::function<void(::RoboCompCommonBehavior::ParameterList)> response,
                          ::std::function<void(::std::exception_ptr)> ex = nullptr,
                          ::std::function<void(bool)> sent = nullptr,
                          const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompCommonBehavior::ParameterList>(response, ex, sent, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_getParameterList, context);
    }

    void _iceI_getParameterList(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompCommonBehavior::ParameterList>>&, const ::Ice::Context&);

    int getPeriod(const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<int>(true, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_getPeriod, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getPeriodAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<int>>().get_future())
    {
        return _makePromiseOutgoing<int, P>(false, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_getPeriod, context);
    }

    ::std::function<void()>
    getPeriodAsync(::std::function<void(int)> response,
                   ::std::function<void(::std::exception_ptr)> ex = nullptr,
                   ::std::function<void(bool)> sent = nullptr,
                   const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<int>(response, ex, sent, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_getPeriod, context);
    }

    void _iceI_getPeriod(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, const ::Ice::Context&);

    ::RoboCompCommonBehavior::State getState(const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::RoboCompCommonBehavior::State>(true, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_getState, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getStateAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompCommonBehavior::State>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompCommonBehavior::State, P>(false, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_getState, context);
    }

    ::std::function<void()>
    getStateAsync(::std::function<void(::RoboCompCommonBehavior::State)> response,
                  ::std::function<void(::std::exception_ptr)> ex = nullptr,
                  ::std::function<void(bool)> sent = nullptr,
                  const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompCommonBehavior::State>(response, ex, sent, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_getState, context);
    }

    void _iceI_getState(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompCommonBehavior::State>>&, const ::Ice::Context&);

    void killYourSelf(const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_killYourSelf, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto killYourSelfAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_killYourSelf, context);
    }

    ::std::function<void()>
    killYourSelfAsync(::std::function<void()> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_killYourSelf, context);
    }

    void _iceI_killYourSelf(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::Ice::Context&);

    void reloadConfig(const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_reloadConfig, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto reloadConfigAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_reloadConfig, context);
    }

    ::std::function<void()>
    reloadConfigAsync(::std::function<void()> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_reloadConfig, context);
    }

    void _iceI_reloadConfig(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::Ice::Context&);

    void setParameterList(const ::RoboCompCommonBehavior::ParameterList& iceP_l, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_setParameterList, iceP_l, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto setParameterListAsync(const ::RoboCompCommonBehavior::ParameterList& iceP_l, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_setParameterList, iceP_l, context);
    }

    ::std::function<void()>
    setParameterListAsync(const ::RoboCompCommonBehavior::ParameterList& iceP_l,
                          ::std::function<void()> response,
                          ::std::function<void(::std::exception_ptr)> ex = nullptr,
                          ::std::function<void(bool)> sent = nullptr,
                          const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_setParameterList, iceP_l, context);
    }

    void _iceI_setParameterList(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::RoboCompCommonBehavior::ParameterList&, const ::Ice::Context&);

    void setPeriod(int iceP_period, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_setPeriod, iceP_period, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto setPeriodAsync(int iceP_period, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_setPeriod, iceP_period, context);
    }

    ::std::function<void()>
    setPeriodAsync(int iceP_period,
                   ::std::function<void()> response,
                   ::std::function<void(::std::exception_ptr)> ex = nullptr,
                   ::std::function<void(bool)> sent = nullptr,
                   const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_setPeriod, iceP_period, context);
    }

    void _iceI_setPeriod(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, int, const ::Ice::Context&);

    int timeAwake(const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<int>(true, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_timeAwake, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto timeAwakeAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<int>>().get_future())
    {
        return _makePromiseOutgoing<int, P>(false, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_timeAwake, context);
    }

    ::std::function<void()>
    timeAwakeAsync(::std::function<void(int)> response,
                   ::std::function<void(::std::exception_ptr)> ex = nullptr,
                   ::std::function<void(bool)> sent = nullptr,
                   const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<int>(response, ex, sent, this, &RoboCompCommonBehavior::CommonBehaviorPrx::_iceI_timeAwake, context);
    }

    void _iceI_timeAwake(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, const ::Ice::Context&);

    static const ::std::string& ice_staticId();

protected:

    CommonBehaviorPrx() = default;
    friend ::std::shared_ptr<CommonBehaviorPrx> IceInternal::createProxy<CommonBehaviorPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
};

}

namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompCommonBehavior::State>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 1;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits<::RoboCompCommonBehavior::Parameter>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 3;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompCommonBehavior::Parameter, S>
{
    static void read(S* istr, ::RoboCompCommonBehavior::Parameter& v)
    {
        istr->readAll(v.editable, v.value, v.type);
    }
};

}

namespace RoboCompCommonBehavior
{

using CommonBehaviorPtr = ::std::shared_ptr<CommonBehavior>;
using CommonBehaviorPrxPtr = ::std::shared_ptr<CommonBehaviorPrx>;

}

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompCommonBehavior
{

class CommonBehavior;
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompCommonBehavior::CommonBehavior>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompCommonBehavior::CommonBehavior*);

}

}

namespace RoboCompCommonBehavior
{

class CommonBehavior;
::Ice::Object* upCast(::RoboCompCommonBehavior::CommonBehavior*);
typedef ::IceInternal::Handle< ::RoboCompCommonBehavior::CommonBehavior> CommonBehaviorPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompCommonBehavior::CommonBehavior> CommonBehaviorPrx;
typedef CommonBehaviorPrx CommonBehaviorPrxPtr;
void _icePatchObjectPtr(CommonBehaviorPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompCommonBehavior
{

enum State
{
    Starting,
    Running
};

struct Parameter
{
    bool editable;
    ::std::string value;
    ::std::string type;

    bool operator==(const Parameter& rhs_) const
    {
        if(this == &rhs_)
        {
            return true;
        }
        if(editable != rhs_.editable)
        {
            return false;
        }
        if(value != rhs_.value)
        {
            return false;
        }
        if(type != rhs_.type)
        {
            return false;
        }
        return true;
    }

    bool operator<(const Parameter& rhs_) const
    {
        if(this == &rhs_)
        {
            return false;
        }
        if(editable < rhs_.editable)
        {
            return true;
        }
        else if(rhs_.editable < editable)
        {
            return false;
        }
        if(value < rhs_.value)
        {
            return true;
        }
        else if(rhs_.value < value)
        {
            return false;
        }
        if(type < rhs_.type)
        {
            return true;
        }
        else if(rhs_.type < type)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const Parameter& rhs_) const
    {
        return !operator==(rhs_);
    }
    bool operator<=(const Parameter& rhs_) const
    {
        return operator<(rhs_) || operator==(rhs_);
    }
    bool operator>(const Parameter& rhs_) const
    {
        return !operator<(rhs_) && !operator==(rhs_);
    }
    bool operator>=(const Parameter& rhs_) const
    {
        return !operator<(rhs_);
    }
};

typedef ::std::map< ::std::string, ::RoboCompCommonBehavior::Parameter> ParameterList;

}

namespace RoboCompCommonBehavior
{

class Callback_CommonBehavior_getParameterList_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CommonBehavior_getParameterList_Base> Callback_CommonBehavior_getParameterListPtr;

class Callback_CommonBehavior_getPeriod_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CommonBehavior_getPeriod_Base> Callback_CommonBehavior_getPeriodPtr;

class Callback_CommonBehavior_getState_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CommonBehavior_getState_Base> Callback_CommonBehavior_getStatePtr;

class Callback_CommonBehavior_killYourSelf_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CommonBehavior_killYourSelf_Base> Callback_CommonBehavior_killYourSelfPtr;

class Callback_CommonBehavior_reloadConfig_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CommonBehavior_reloadConfig_Base> Callback_CommonBehavior_reloadConfigPtr;

class Callback_CommonBehavior_setParameterList_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CommonBehavior_setParameterList_Base> Callback_CommonBehavior_setParameterListPtr;

class Callback_CommonBehavior_setPeriod_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CommonBehavior_setPeriod_Base> Callback_CommonBehavior_setPeriodPtr;

class Callback_CommonBehavior_timeAwake_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CommonBehavior_timeAwake_Base> Callback_CommonBehavior_timeAwakePtr;

}

namespace IceProxy
{

namespace RoboCompCommonBehavior
{

class CommonBehavior : public virtual ::Ice::Proxy<CommonBehavior, ::IceProxy::Ice::Object>
{
public:

    ::RoboCompCommonBehavior::ParameterList getParameterList(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getParameterList(_iceI_begin_getParameterList(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getParameterList(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getParameterList(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getParameterList(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getParameterList(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getParameterList(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getParameterList(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getParameterList(const ::RoboCompCommonBehavior::Callback_CommonBehavior_getParameterListPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getParameterList(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getParameterList(const ::Ice::Context& context, const ::RoboCompCommonBehavior::Callback_CommonBehavior_getParameterListPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getParameterList(context, del, cookie);
    }

    ::RoboCompCommonBehavior::ParameterList end_getParameterList(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getParameterList(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::Ice::Int getPeriod(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getPeriod(_iceI_begin_getPeriod(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getPeriod(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getPeriod(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getPeriod(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getPeriod(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getPeriod(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getPeriod(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getPeriod(const ::RoboCompCommonBehavior::Callback_CommonBehavior_getPeriodPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getPeriod(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getPeriod(const ::Ice::Context& context, const ::RoboCompCommonBehavior::Callback_CommonBehavior_getPeriodPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getPeriod(context, del, cookie);
    }

    ::Ice::Int end_getPeriod(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getPeriod(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::RoboCompCommonBehavior::State getState(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getState(_iceI_begin_getState(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getState(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getState(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getState(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getState(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::RoboCompCommonBehavior::Callback_CommonBehavior_getStatePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getState(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::Ice::Context& context, const ::RoboCompCommonBehavior::Callback_CommonBehavior_getStatePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getState(context, del, cookie);
    }

    ::RoboCompCommonBehavior::State end_getState(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getState(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void killYourSelf(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_killYourSelf(_iceI_begin_killYourSelf(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_killYourSelf(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_killYourSelf(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_killYourSelf(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_killYourSelf(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_killYourSelf(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_killYourSelf(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_killYourSelf(const ::RoboCompCommonBehavior::Callback_CommonBehavior_killYourSelfPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_killYourSelf(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_killYourSelf(const ::Ice::Context& context, const ::RoboCompCommonBehavior::Callback_CommonBehavior_killYourSelfPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_killYourSelf(context, del, cookie);
    }

    void end_killYourSelf(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_killYourSelf(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void reloadConfig(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_reloadConfig(_iceI_begin_reloadConfig(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_reloadConfig(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_reloadConfig(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_reloadConfig(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_reloadConfig(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_reloadConfig(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_reloadConfig(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_reloadConfig(const ::RoboCompCommonBehavior::Callback_CommonBehavior_reloadConfigPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_reloadConfig(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_reloadConfig(const ::Ice::Context& context, const ::RoboCompCommonBehavior::Callback_CommonBehavior_reloadConfigPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_reloadConfig(context, del, cookie);
    }

    void end_reloadConfig(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_reloadConfig(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void setParameterList(const ::RoboCompCommonBehavior::ParameterList& iceP_l, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_setParameterList(_iceI_begin_setParameterList(iceP_l, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_setParameterList(const ::RoboCompCommonBehavior::ParameterList& iceP_l, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_setParameterList(iceP_l, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setParameterList(const ::RoboCompCommonBehavior::ParameterList& iceP_l, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setParameterList(iceP_l, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setParameterList(const ::RoboCompCommonBehavior::ParameterList& iceP_l, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setParameterList(iceP_l, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setParameterList(const ::RoboCompCommonBehavior::ParameterList& iceP_l, const ::RoboCompCommonBehavior::Callback_CommonBehavior_setParameterListPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setParameterList(iceP_l, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setParameterList(const ::RoboCompCommonBehavior::ParameterList& iceP_l, const ::Ice::Context& context, const ::RoboCompCommonBehavior::Callback_CommonBehavior_setParameterListPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setParameterList(iceP_l, context, del, cookie);
    }

    void end_setParameterList(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_setParameterList(const ::RoboCompCommonBehavior::ParameterList&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void setPeriod(::Ice::Int iceP_period, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_setPeriod(_iceI_begin_setPeriod(iceP_period, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_setPeriod(::Ice::Int iceP_period, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_setPeriod(iceP_period, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setPeriod(::Ice::Int iceP_period, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setPeriod(iceP_period, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setPeriod(::Ice::Int iceP_period, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setPeriod(iceP_period, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setPeriod(::Ice::Int iceP_period, const ::RoboCompCommonBehavior::Callback_CommonBehavior_setPeriodPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setPeriod(iceP_period, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setPeriod(::Ice::Int iceP_period, const ::Ice::Context& context, const ::RoboCompCommonBehavior::Callback_CommonBehavior_setPeriodPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setPeriod(iceP_period, context, del, cookie);
    }

    void end_setPeriod(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_setPeriod(::Ice::Int, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::Ice::Int timeAwake(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_timeAwake(_iceI_begin_timeAwake(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_timeAwake(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_timeAwake(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_timeAwake(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_timeAwake(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_timeAwake(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_timeAwake(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_timeAwake(const ::RoboCompCommonBehavior::Callback_CommonBehavior_timeAwakePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_timeAwake(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_timeAwake(const ::Ice::Context& context, const ::RoboCompCommonBehavior::Callback_CommonBehavior_timeAwakePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_timeAwake(context, del, cookie);
    }

    ::Ice::Int end_timeAwake(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_timeAwake(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    static const ::std::string& ice_staticId();

protected:

    virtual ::IceProxy::Ice::Object* _newInstance() const;
};

}

}

namespace RoboCompCommonBehavior
{

class CommonBehavior : public virtual ::Ice::Object
{
public:

    typedef CommonBehaviorPrx ProxyType;
    typedef CommonBehaviorPtr PointerType;

    virtual ~CommonBehavior();

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::emptyCurrent) const;

    static const ::std::string& ice_staticId();

    virtual ::RoboCompCommonBehavior::ParameterList getParameterList(const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_getParameterList(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int getPeriod(const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_getPeriod(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::RoboCompCommonBehavior::State getState(const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_getState(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void killYourSelf(const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_killYourSelf(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void reloadConfig(const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_reloadConfig(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setParameterList(const ::RoboCompCommonBehavior::ParameterList&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_setParameterList(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setPeriod(::Ice::Int, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_setPeriod(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int timeAwake(const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_timeAwake(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:

    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
};

inline bool operator==(const CommonBehavior& lhs, const CommonBehavior& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const CommonBehavior& lhs, const CommonBehavior& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}

}

namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompCommonBehavior::State>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 1;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits< ::RoboCompCommonBehavior::Parameter>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 3;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompCommonBehavior::Parameter, S>
{
    static void write(S* ostr, const ::RoboCompCommonBehavior::Parameter& v)
    {
        ostr->write(v.editable);
        ostr->write(v.value);
        ostr->write(v.type);
    }
};

template<typename S>
struct StreamReader< ::RoboCompCommonBehavior::Parameter, S>
{
    static void read(S* istr, ::RoboCompCommonBehavior::Parameter& v)
    {
        istr->read(v.editable);
        istr->read(v.value);
        istr->read(v.type);
    }
};

}

namespace RoboCompCommonBehavior
{

template<class T>
class CallbackNC_CommonBehavior_getParameterList : public Callback_CommonBehavior_getParameterList_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::RoboCompCommonBehavior::ParameterList&);

    CallbackNC_CommonBehavior_getParameterList(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompCommonBehavior::CommonBehaviorPrx proxy = ::RoboCompCommonBehavior::CommonBehaviorPrx::uncheckedCast(result->getProxy());
        ::RoboCompCommonBehavior::ParameterList ret;
        try
        {
            ret = proxy->end_getParameterList(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }

private:

    Response _response;
};

template<class T> Callback_CommonBehavior_getParameterListPtr
newCallback_CommonBehavior_getParameterList(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::RoboCompCommonBehavior::ParameterList&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_getParameterList<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CommonBehavior_getParameterListPtr
newCallback_CommonBehavior_getParameterList(T* instance, void (T::*cb)(const ::RoboCompCommonBehavior::ParameterList&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_getParameterList<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_CommonBehavior_getParameterList : public Callback_CommonBehavior_getParameterList_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::RoboCompCommonBehavior::ParameterList&, const CT&);

    Callback_CommonBehavior_getParameterList(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompCommonBehavior::CommonBehaviorPrx proxy = ::RoboCompCommonBehavior::CommonBehaviorPrx::uncheckedCast(result->getProxy());
        ::RoboCompCommonBehavior::ParameterList ret;
        try
        {
            ret = proxy->end_getParameterList(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_CommonBehavior_getParameterListPtr
newCallback_CommonBehavior_getParameterList(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::RoboCompCommonBehavior::ParameterList&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_getParameterList<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_getParameterListPtr
newCallback_CommonBehavior_getParameterList(T* instance, void (T::*cb)(const ::RoboCompCommonBehavior::ParameterList&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_getParameterList<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_CommonBehavior_getPeriod : public Callback_CommonBehavior_getPeriod_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_CommonBehavior_getPeriod(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompCommonBehavior::CommonBehaviorPrx proxy = ::RoboCompCommonBehavior::CommonBehaviorPrx::uncheckedCast(result->getProxy());
        ::Ice::Int ret;
        try
        {
            ret = proxy->end_getPeriod(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }

private:

    Response _response;
};

template<class T> Callback_CommonBehavior_getPeriodPtr
newCallback_CommonBehavior_getPeriod(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_getPeriod<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CommonBehavior_getPeriodPtr
newCallback_CommonBehavior_getPeriod(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_getPeriod<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_CommonBehavior_getPeriod : public Callback_CommonBehavior_getPeriod_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_CommonBehavior_getPeriod(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompCommonBehavior::CommonBehaviorPrx proxy = ::RoboCompCommonBehavior::CommonBehaviorPrx::uncheckedCast(result->getProxy());
        ::Ice::Int ret;
        try
        {
            ret = proxy->end_getPeriod(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_CommonBehavior_getPeriodPtr
newCallback_CommonBehavior_getPeriod(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_getPeriod<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_getPeriodPtr
newCallback_CommonBehavior_getPeriod(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_getPeriod<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_CommonBehavior_getState : public Callback_CommonBehavior_getState_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::RoboCompCommonBehavior::State);

    CallbackNC_CommonBehavior_getState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompCommonBehavior::CommonBehaviorPrx proxy = ::RoboCompCommonBehavior::CommonBehaviorPrx::uncheckedCast(result->getProxy());
        ::RoboCompCommonBehavior::State ret;
        try
        {
            ret = proxy->end_getState(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }

private:

    Response _response;
};

template<class T> Callback_CommonBehavior_getStatePtr
newCallback_CommonBehavior_getState(const IceUtil::Handle<T>& instance, void (T::*cb)(::RoboCompCommonBehavior::State), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_getState<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CommonBehavior_getStatePtr
newCallback_CommonBehavior_getState(T* instance, void (T::*cb)(::RoboCompCommonBehavior::State), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_getState<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_CommonBehavior_getState : public Callback_CommonBehavior_getState_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::RoboCompCommonBehavior::State, const CT&);

    Callback_CommonBehavior_getState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompCommonBehavior::CommonBehaviorPrx proxy = ::RoboCompCommonBehavior::CommonBehaviorPrx::uncheckedCast(result->getProxy());
        ::RoboCompCommonBehavior::State ret;
        try
        {
            ret = proxy->end_getState(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_CommonBehavior_getStatePtr
newCallback_CommonBehavior_getState(const IceUtil::Handle<T>& instance, void (T::*cb)(::RoboCompCommonBehavior::State, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_getState<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_getStatePtr
newCallback_CommonBehavior_getState(T* instance, void (T::*cb)(::RoboCompCommonBehavior::State, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_getState<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_CommonBehavior_killYourSelf : public Callback_CommonBehavior_killYourSelf_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_CommonBehavior_killYourSelf(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_CommonBehavior_killYourSelfPtr
newCallback_CommonBehavior_killYourSelf(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_killYourSelf<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CommonBehavior_killYourSelfPtr
newCallback_CommonBehavior_killYourSelf(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_killYourSelf<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_CommonBehavior_killYourSelfPtr
newCallback_CommonBehavior_killYourSelf(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_killYourSelf<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CommonBehavior_killYourSelfPtr
newCallback_CommonBehavior_killYourSelf(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_killYourSelf<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_CommonBehavior_killYourSelf : public Callback_CommonBehavior_killYourSelf_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_CommonBehavior_killYourSelf(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_CommonBehavior_killYourSelfPtr
newCallback_CommonBehavior_killYourSelf(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_killYourSelf<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_killYourSelfPtr
newCallback_CommonBehavior_killYourSelf(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_killYourSelf<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_killYourSelfPtr
newCallback_CommonBehavior_killYourSelf(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_killYourSelf<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_killYourSelfPtr
newCallback_CommonBehavior_killYourSelf(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_killYourSelf<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_CommonBehavior_reloadConfig : public Callback_CommonBehavior_reloadConfig_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_CommonBehavior_reloadConfig(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_CommonBehavior_reloadConfigPtr
newCallback_CommonBehavior_reloadConfig(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_reloadConfig<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CommonBehavior_reloadConfigPtr
newCallback_CommonBehavior_reloadConfig(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_reloadConfig<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_CommonBehavior_reloadConfigPtr
newCallback_CommonBehavior_reloadConfig(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_reloadConfig<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CommonBehavior_reloadConfigPtr
newCallback_CommonBehavior_reloadConfig(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_reloadConfig<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_CommonBehavior_reloadConfig : public Callback_CommonBehavior_reloadConfig_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_CommonBehavior_reloadConfig(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_CommonBehavior_reloadConfigPtr
newCallback_CommonBehavior_reloadConfig(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_reloadConfig<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_reloadConfigPtr
newCallback_CommonBehavior_reloadConfig(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_reloadConfig<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_reloadConfigPtr
newCallback_CommonBehavior_reloadConfig(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_reloadConfig<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_reloadConfigPtr
newCallback_CommonBehavior_reloadConfig(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_reloadConfig<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_CommonBehavior_setParameterList : public Callback_CommonBehavior_setParameterList_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_CommonBehavior_setParameterList(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_CommonBehavior_setParameterListPtr
newCallback_CommonBehavior_setParameterList(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_setParameterList<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CommonBehavior_setParameterListPtr
newCallback_CommonBehavior_setParameterList(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_setParameterList<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_CommonBehavior_setParameterListPtr
newCallback_CommonBehavior_setParameterList(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_setParameterList<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CommonBehavior_setParameterListPtr
newCallback_CommonBehavior_setParameterList(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_setParameterList<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_CommonBehavior_setParameterList : public Callback_CommonBehavior_setParameterList_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_CommonBehavior_setParameterList(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_CommonBehavior_setParameterListPtr
newCallback_CommonBehavior_setParameterList(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_setParameterList<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_setParameterListPtr
newCallback_CommonBehavior_setParameterList(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_setParameterList<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_setParameterListPtr
newCallback_CommonBehavior_setParameterList(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_setParameterList<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_setParameterListPtr
newCallback_CommonBehavior_setParameterList(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_setParameterList<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_CommonBehavior_setPeriod : public Callback_CommonBehavior_setPeriod_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_CommonBehavior_setPeriod(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_CommonBehavior_setPeriodPtr
newCallback_CommonBehavior_setPeriod(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_setPeriod<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CommonBehavior_setPeriodPtr
newCallback_CommonBehavior_setPeriod(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_setPeriod<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_CommonBehavior_setPeriodPtr
newCallback_CommonBehavior_setPeriod(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_setPeriod<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CommonBehavior_setPeriodPtr
newCallback_CommonBehavior_setPeriod(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_setPeriod<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_CommonBehavior_setPeriod : public Callback_CommonBehavior_setPeriod_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_CommonBehavior_setPeriod(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_CommonBehavior_setPeriodPtr
newCallback_CommonBehavior_setPeriod(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_setPeriod<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_setPeriodPtr
newCallback_CommonBehavior_setPeriod(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_setPeriod<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_setPeriodPtr
newCallback_CommonBehavior_setPeriod(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_setPeriod<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_setPeriodPtr
newCallback_CommonBehavior_setPeriod(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_setPeriod<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_CommonBehavior_timeAwake : public Callback_CommonBehavior_timeAwake_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_CommonBehavior_timeAwake(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompCommonBehavior::CommonBehaviorPrx proxy = ::RoboCompCommonBehavior::CommonBehaviorPrx::uncheckedCast(result->getProxy());
        ::Ice::Int ret;
        try
        {
            ret = proxy->end_timeAwake(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }

private:

    Response _response;
};

template<class T> Callback_CommonBehavior_timeAwakePtr
newCallback_CommonBehavior_timeAwake(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_timeAwake<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CommonBehavior_timeAwakePtr
newCallback_CommonBehavior_timeAwake(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CommonBehavior_timeAwake<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_CommonBehavior_timeAwake : public Callback_CommonBehavior_timeAwake_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_CommonBehavior_timeAwake(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompCommonBehavior::CommonBehaviorPrx proxy = ::RoboCompCommonBehavior::CommonBehaviorPrx::uncheckedCast(result->getProxy());
        ::Ice::Int ret;
        try
        {
            ret = proxy->end_timeAwake(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_CommonBehavior_timeAwakePtr
newCallback_CommonBehavior_timeAwake(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_timeAwake<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CommonBehavior_timeAwakePtr
newCallback_CommonBehavior_timeAwake(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CommonBehavior_timeAwake<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
