// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `GoalPublisher.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <GoalPublisher.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompGoalPublisher_GoalPublisher_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGoalPublisher::GoalPublisher"
};
const ::std::string iceC_RoboCompGoalPublisher_GoalPublisher_ops[] =
{
    "goalupdated",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompGoalPublisher_GoalPublisher_goalupdated_name = "goalupdated";

}

bool
RoboCompGoalPublisher::GoalPublisher::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompGoalPublisher_GoalPublisher_ids, iceC_RoboCompGoalPublisher_GoalPublisher_ids + 2, s);
}

::std::vector<::std::string>
RoboCompGoalPublisher::GoalPublisher::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompGoalPublisher_GoalPublisher_ids[0], &iceC_RoboCompGoalPublisher_GoalPublisher_ids[2]);
}

::std::string
RoboCompGoalPublisher::GoalPublisher::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompGoalPublisher::GoalPublisher::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompGoalPublisher::GoalPublisher";
    return typeId;
}

bool
RoboCompGoalPublisher::GoalPublisher::_iceD_goalupdated(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompGoalPublisher::GoalT iceP_goal;
    istr->readAll(iceP_goal);
    inS.endReadParams();
    this->goalupdated(::std::move(iceP_goal), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompGoalPublisher::GoalPublisher::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompGoalPublisher_GoalPublisher_ops, iceC_RoboCompGoalPublisher_GoalPublisher_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompGoalPublisher_GoalPublisher_ops)
    {
        case 0:
        {
            return _iceD_goalupdated(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompGoalPublisher::GoalPublisherPrx::_iceI_goalupdated(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompGoalPublisher::GoalT& iceP_goal, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompGoalPublisher_GoalPublisher_goalupdated_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_goal);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
RoboCompGoalPublisher::GoalPublisherPrx::_newInstance() const
{
    return ::IceInternal::createProxy<GoalPublisherPrx>();
}

const ::std::string&
RoboCompGoalPublisher::GoalPublisherPrx::ice_staticId()
{
    return RoboCompGoalPublisher::GoalPublisher::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompGoalPublisher_GoalPublisher_goalupdated_name = "goalupdated";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompGoalPublisher::upCast(::IceProxy::RoboCompGoalPublisher::GoalPublisher* p) { return p; }

void
::IceProxy::RoboCompGoalPublisher::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompGoalPublisher::GoalPublisher>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompGoalPublisher::GoalPublisher;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGoalPublisher::GoalPublisher::_iceI_begin_goalupdated(const ::RoboCompGoalPublisher::GoalT& iceP_goal, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGoalPublisher_GoalPublisher_goalupdated_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGoalPublisher_GoalPublisher_goalupdated_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_goal);
        result->endWriteParams();
        result->invoke(iceC_RoboCompGoalPublisher_GoalPublisher_goalupdated_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompGoalPublisher::GoalPublisher::end_goalupdated(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompGoalPublisher_GoalPublisher_goalupdated_name);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompGoalPublisher::GoalPublisher::_newInstance() const
{
    return new GoalPublisher;
}

const ::std::string&
IceProxy::RoboCompGoalPublisher::GoalPublisher::ice_staticId()
{
    return ::RoboCompGoalPublisher::GoalPublisher::ice_staticId();
}

RoboCompGoalPublisher::GoalPublisher::~GoalPublisher()
{
}

::Ice::Object* RoboCompGoalPublisher::upCast(::RoboCompGoalPublisher::GoalPublisher* p) { return p; }


namespace
{
const ::std::string iceC_RoboCompGoalPublisher_GoalPublisher_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGoalPublisher::GoalPublisher"
};

}

bool
RoboCompGoalPublisher::GoalPublisher::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompGoalPublisher_GoalPublisher_ids, iceC_RoboCompGoalPublisher_GoalPublisher_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompGoalPublisher::GoalPublisher::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompGoalPublisher_GoalPublisher_ids[0], &iceC_RoboCompGoalPublisher_GoalPublisher_ids[2]);
}

const ::std::string&
RoboCompGoalPublisher::GoalPublisher::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompGoalPublisher::GoalPublisher::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompGoalPublisher::GoalPublisher";
    return typeId;
#else
    return iceC_RoboCompGoalPublisher_GoalPublisher_ids[1];
#endif
}

bool
RoboCompGoalPublisher::GoalPublisher::_iceD_goalupdated(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompGoalPublisher::GoalT iceP_goal;
    istr->read(iceP_goal);
    inS.endReadParams();
    this->goalupdated(iceP_goal, current);
    inS.writeEmptyParams();
    return true;
}

namespace
{
const ::std::string iceC_RoboCompGoalPublisher_GoalPublisher_all[] =
{
    "goalupdated",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

bool
RoboCompGoalPublisher::GoalPublisher::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompGoalPublisher_GoalPublisher_all, iceC_RoboCompGoalPublisher_GoalPublisher_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompGoalPublisher_GoalPublisher_all)
    {
        case 0:
        {
            return _iceD_goalupdated(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompGoalPublisher::GoalPublisher::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::RoboCompGoalPublisher::GoalPublisher, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompGoalPublisher::GoalPublisher::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::RoboCompGoalPublisher::GoalPublisher, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
RoboCompGoalPublisher::_icePatchObjectPtr(GoalPublisherPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompGoalPublisher::GoalPublisherPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompGoalPublisher::GoalPublisher::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
