// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `JoystickAdapter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <JoystickAdapter.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompJoystickAdapter_JoystickAdapter_ids[2] =
{
    "::Ice::Object",
    "::RoboCompJoystickAdapter::JoystickAdapter"
};
const ::std::string iceC_RoboCompJoystickAdapter_JoystickAdapter_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendData"
};
const ::std::string iceC_RoboCompJoystickAdapter_JoystickAdapter_sendData_name = "sendData";

}

bool
RoboCompJoystickAdapter::JoystickAdapter::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompJoystickAdapter_JoystickAdapter_ids, iceC_RoboCompJoystickAdapter_JoystickAdapter_ids + 2, s);
}

::std::vector<::std::string>
RoboCompJoystickAdapter::JoystickAdapter::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompJoystickAdapter_JoystickAdapter_ids[0], &iceC_RoboCompJoystickAdapter_JoystickAdapter_ids[2]);
}

::std::string
RoboCompJoystickAdapter::JoystickAdapter::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompJoystickAdapter::JoystickAdapter::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompJoystickAdapter::JoystickAdapter";
    return typeId;
}

bool
RoboCompJoystickAdapter::JoystickAdapter::_iceD_sendData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Idempotent, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompJoystickAdapter::TData iceP_data;
    istr->readAll(iceP_data);
    inS.endReadParams();
    this->sendData(::std::move(iceP_data), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompJoystickAdapter::JoystickAdapter::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompJoystickAdapter_JoystickAdapter_ops, iceC_RoboCompJoystickAdapter_JoystickAdapter_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompJoystickAdapter_JoystickAdapter_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_sendData(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompJoystickAdapter::JoystickAdapterPrx::_iceI_sendData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompJoystickAdapter::TData& iceP_data, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompJoystickAdapter_JoystickAdapter_sendData_name, ::Ice::OperationMode::Idempotent, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_data);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
RoboCompJoystickAdapter::JoystickAdapterPrx::_newInstance() const
{
    return ::IceInternal::createProxy<JoystickAdapterPrx>();
}

const ::std::string&
RoboCompJoystickAdapter::JoystickAdapterPrx::ice_staticId()
{
    return RoboCompJoystickAdapter::JoystickAdapter::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompJoystickAdapter_JoystickAdapter_sendData_name = "sendData";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompJoystickAdapter::upCast(::IceProxy::RoboCompJoystickAdapter::JoystickAdapter* p) { return p; }

void
::IceProxy::RoboCompJoystickAdapter::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompJoystickAdapter::JoystickAdapter>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompJoystickAdapter::JoystickAdapter;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompJoystickAdapter::JoystickAdapter::_iceI_begin_sendData(const ::RoboCompJoystickAdapter::TData& iceP_data, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompJoystickAdapter_JoystickAdapter_sendData_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompJoystickAdapter_JoystickAdapter_sendData_name, ::Ice::Idempotent, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_data);
        result->endWriteParams();
        result->invoke(iceC_RoboCompJoystickAdapter_JoystickAdapter_sendData_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompJoystickAdapter::JoystickAdapter::end_sendData(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompJoystickAdapter_JoystickAdapter_sendData_name);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompJoystickAdapter::JoystickAdapter::_newInstance() const
{
    return new JoystickAdapter;
}

const ::std::string&
IceProxy::RoboCompJoystickAdapter::JoystickAdapter::ice_staticId()
{
    return ::RoboCompJoystickAdapter::JoystickAdapter::ice_staticId();
}

RoboCompJoystickAdapter::JoystickAdapter::~JoystickAdapter()
{
}

::Ice::Object* RoboCompJoystickAdapter::upCast(::RoboCompJoystickAdapter::JoystickAdapter* p) { return p; }


namespace
{
const ::std::string iceC_RoboCompJoystickAdapter_JoystickAdapter_ids[2] =
{
    "::Ice::Object",
    "::RoboCompJoystickAdapter::JoystickAdapter"
};

}

bool
RoboCompJoystickAdapter::JoystickAdapter::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompJoystickAdapter_JoystickAdapter_ids, iceC_RoboCompJoystickAdapter_JoystickAdapter_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompJoystickAdapter::JoystickAdapter::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompJoystickAdapter_JoystickAdapter_ids[0], &iceC_RoboCompJoystickAdapter_JoystickAdapter_ids[2]);
}

const ::std::string&
RoboCompJoystickAdapter::JoystickAdapter::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompJoystickAdapter::JoystickAdapter::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompJoystickAdapter::JoystickAdapter";
    return typeId;
#else
    return iceC_RoboCompJoystickAdapter_JoystickAdapter_ids[1];
#endif
}

bool
RoboCompJoystickAdapter::JoystickAdapter::_iceD_sendData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Idempotent, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompJoystickAdapter::TData iceP_data;
    istr->read(iceP_data);
    inS.endReadParams();
    this->sendData(iceP_data, current);
    inS.writeEmptyParams();
    return true;
}

namespace
{
const ::std::string iceC_RoboCompJoystickAdapter_JoystickAdapter_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendData"
};

}

bool
RoboCompJoystickAdapter::JoystickAdapter::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompJoystickAdapter_JoystickAdapter_all, iceC_RoboCompJoystickAdapter_JoystickAdapter_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompJoystickAdapter_JoystickAdapter_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_sendData(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompJoystickAdapter::JoystickAdapter::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::RoboCompJoystickAdapter::JoystickAdapter, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompJoystickAdapter::JoystickAdapter::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::RoboCompJoystickAdapter::JoystickAdapter, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
RoboCompJoystickAdapter::_icePatchObjectPtr(JoystickAdapterPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompJoystickAdapter::JoystickAdapterPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompJoystickAdapter::JoystickAdapter::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
