// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `ObjectDetector.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <ObjectDetector.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompObjectDetector_ObjectDetector_ids[2] =
{
    "::Ice::Object",
    "::RoboCompObjectDetector::ObjectDetector"
};
const ::std::string iceC_RoboCompObjectDetector_ObjectDetector_ops[] =
{
    "gotobjects",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompObjectDetector_ObjectDetector_gotobjects_name = "gotobjects";

}

bool
RoboCompObjectDetector::ObjectDetector::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompObjectDetector_ObjectDetector_ids, iceC_RoboCompObjectDetector_ObjectDetector_ids + 2, s);
}

::std::vector<::std::string>
RoboCompObjectDetector::ObjectDetector::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompObjectDetector_ObjectDetector_ids[0], &iceC_RoboCompObjectDetector_ObjectDetector_ids[2]);
}

::std::string
RoboCompObjectDetector::ObjectDetector::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompObjectDetector::ObjectDetector::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompObjectDetector::ObjectDetector";
    return typeId;
}

bool
RoboCompObjectDetector::ObjectDetector::_iceD_gotobjects(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompObjectDetector::ObjectList iceP_lst;
    istr->readAll(iceP_lst);
    inS.endReadParams();
    this->gotobjects(::std::move(iceP_lst), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompObjectDetector::ObjectDetector::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompObjectDetector_ObjectDetector_ops, iceC_RoboCompObjectDetector_ObjectDetector_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompObjectDetector_ObjectDetector_ops)
    {
        case 0:
        {
            return _iceD_gotobjects(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompObjectDetector::ObjectDetectorPrx::_iceI_gotobjects(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompObjectDetector::ObjectList& iceP_lst, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompObjectDetector_ObjectDetector_gotobjects_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_lst);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
RoboCompObjectDetector::ObjectDetectorPrx::_newInstance() const
{
    return ::IceInternal::createProxy<ObjectDetectorPrx>();
}

const ::std::string&
RoboCompObjectDetector::ObjectDetectorPrx::ice_staticId()
{
    return RoboCompObjectDetector::ObjectDetector::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompObjectDetector_ObjectDetector_gotobjects_name = "gotobjects";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompObjectDetector::upCast(::IceProxy::RoboCompObjectDetector::ObjectDetector* p) { return p; }

void
::IceProxy::RoboCompObjectDetector::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompObjectDetector::ObjectDetector>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompObjectDetector::ObjectDetector;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompObjectDetector::ObjectDetector::_iceI_begin_gotobjects(const ::RoboCompObjectDetector::ObjectList& iceP_lst, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompObjectDetector_ObjectDetector_gotobjects_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompObjectDetector_ObjectDetector_gotobjects_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_lst);
        result->endWriteParams();
        result->invoke(iceC_RoboCompObjectDetector_ObjectDetector_gotobjects_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompObjectDetector::ObjectDetector::end_gotobjects(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompObjectDetector_ObjectDetector_gotobjects_name);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompObjectDetector::ObjectDetector::_newInstance() const
{
    return new ObjectDetector;
}

const ::std::string&
IceProxy::RoboCompObjectDetector::ObjectDetector::ice_staticId()
{
    return ::RoboCompObjectDetector::ObjectDetector::ice_staticId();
}

RoboCompObjectDetector::ObjectDetector::~ObjectDetector()
{
}

::Ice::Object* RoboCompObjectDetector::upCast(::RoboCompObjectDetector::ObjectDetector* p) { return p; }


namespace
{
const ::std::string iceC_RoboCompObjectDetector_ObjectDetector_ids[2] =
{
    "::Ice::Object",
    "::RoboCompObjectDetector::ObjectDetector"
};

}

bool
RoboCompObjectDetector::ObjectDetector::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompObjectDetector_ObjectDetector_ids, iceC_RoboCompObjectDetector_ObjectDetector_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompObjectDetector::ObjectDetector::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompObjectDetector_ObjectDetector_ids[0], &iceC_RoboCompObjectDetector_ObjectDetector_ids[2]);
}

const ::std::string&
RoboCompObjectDetector::ObjectDetector::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompObjectDetector::ObjectDetector::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompObjectDetector::ObjectDetector";
    return typeId;
#else
    return iceC_RoboCompObjectDetector_ObjectDetector_ids[1];
#endif
}

bool
RoboCompObjectDetector::ObjectDetector::_iceD_gotobjects(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompObjectDetector::ObjectList iceP_lst;
    istr->read(iceP_lst);
    inS.endReadParams();
    this->gotobjects(iceP_lst, current);
    inS.writeEmptyParams();
    return true;
}

namespace
{
const ::std::string iceC_RoboCompObjectDetector_ObjectDetector_all[] =
{
    "gotobjects",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

bool
RoboCompObjectDetector::ObjectDetector::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompObjectDetector_ObjectDetector_all, iceC_RoboCompObjectDetector_ObjectDetector_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompObjectDetector_ObjectDetector_all)
    {
        case 0:
        {
            return _iceD_gotobjects(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompObjectDetector::ObjectDetector::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::RoboCompObjectDetector::ObjectDetector, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompObjectDetector::ObjectDetector::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::RoboCompObjectDetector::ObjectDetector, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
RoboCompObjectDetector::_icePatchObjectPtr(ObjectDetectorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompObjectDetector::ObjectDetectorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompObjectDetector::ObjectDetector::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
