// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `OmniRobot.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __OmniRobot_h__
#define __OmniRobot_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/ExceptionHelpers.h>
#include <GenericBase.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompOmniRobot
{

class OmniRobot;
class OmniRobotPrx;

}

namespace RoboCompOmniRobot
{

struct TMechParams
{
    float temp;
    ::std::string device;
    ::std::string handler;
    float maxVelAdv;
    float maxVelRot;

    std::tuple<const float&, const ::std::string&, const ::std::string&, const float&, const float&> ice_tuple() const
    {
        return std::tie(temp, device, handler, maxVelAdv, maxVelRot);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace RoboCompOmniRobot
{

class OmniRobot : public virtual ::Ice::Object
{
public:

    using ProxyType = OmniRobotPrx;

    virtual bool ice_isA(::std::string, const ::Ice::Current&) const override;
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current&) const override;
    virtual ::std::string ice_id(const ::Ice::Current&) const override;

    static const ::std::string& ice_staticId();

    virtual void correctOdometer(int, int, float, const ::Ice::Current&) = 0;
    bool _iceD_correctOdometer(::IceInternal::Incoming&, const ::Ice::Current&);

    struct GetBasePoseResult
    {
        int x;
        int z;
        float alpha;
    };

    virtual void getBasePose(int&, int&, float&, const ::Ice::Current&) = 0;
    bool _iceD_getBasePose(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void getBaseState(::RoboCompGenericBase::TBaseState&, const ::Ice::Current&) = 0;
    bool _iceD_getBaseState(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void resetOdometer(const ::Ice::Current&) = 0;
    bool _iceD_resetOdometer(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setOdometer(::RoboCompGenericBase::TBaseState, const ::Ice::Current&) = 0;
    bool _iceD_setOdometer(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setOdometerPose(int, int, float, const ::Ice::Current&) = 0;
    bool _iceD_setOdometerPose(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setSpeedBase(float, float, float, const ::Ice::Current&) = 0;
    bool _iceD_setSpeedBase(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void stopBase(const ::Ice::Current&) = 0;
    bool _iceD_stopBase(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
};

}

namespace RoboCompOmniRobot
{

class OmniRobotPrx : public virtual ::Ice::Proxy<OmniRobotPrx, ::Ice::ObjectPrx>
{
public:

    void correctOdometer(int iceP_x, int iceP_z, float iceP_alpha, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_correctOdometer, iceP_x, iceP_z, iceP_alpha, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto correctOdometerAsync(int iceP_x, int iceP_z, float iceP_alpha, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_correctOdometer, iceP_x, iceP_z, iceP_alpha, context);
    }

    ::std::function<void()>
    correctOdometerAsync(int iceP_x, int iceP_z, float iceP_alpha,
                         ::std::function<void()> response,
                         ::std::function<void(::std::exception_ptr)> ex = nullptr,
                         ::std::function<void(bool)> sent = nullptr,
                         const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_correctOdometer, iceP_x, iceP_z, iceP_alpha, context);
    }

    void _iceI_correctOdometer(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, int, int, float, const ::Ice::Context&);

    void getBasePose(int& iceP_x, int& iceP_z, float& iceP_alpha, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        auto result = _makePromiseOutgoing<::RoboCompOmniRobot::OmniRobot::GetBasePoseResult>(true, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_getBasePose, context).get();
        iceP_x = result.x;
        iceP_z = result.z;
        iceP_alpha = result.alpha;
    }

    template<template<typename> class P = ::std::promise>
    auto getBasePoseAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompOmniRobot::OmniRobot::GetBasePoseResult>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompOmniRobot::OmniRobot::GetBasePoseResult, P>(false, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_getBasePose, context);
    }

    ::std::function<void()>
    getBasePoseAsync(::std::function<void(int, int, float)> response,
                     ::std::function<void(::std::exception_ptr)> ex = nullptr,
                     ::std::function<void(bool)> sent = nullptr,
                     const ::Ice::Context& context = Ice::noExplicitContext)
    {
        auto responseCb = [response](::RoboCompOmniRobot::OmniRobot::GetBasePoseResult&& result)
        {
            response(result.x, result.z, result.alpha);
        };
        return _makeLamdaOutgoing<::RoboCompOmniRobot::OmniRobot::GetBasePoseResult>(responseCb, ex, sent, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_getBasePose, context);
    }

    void _iceI_getBasePose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompOmniRobot::OmniRobot::GetBasePoseResult>>&, const ::Ice::Context&);

    void getBaseState(::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        iceP_state = _makePromiseOutgoing<::RoboCompGenericBase::TBaseState>(true, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_getBaseState, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getBaseStateAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompGenericBase::TBaseState>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompGenericBase::TBaseState, P>(false, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_getBaseState, context);
    }

    ::std::function<void()>
    getBaseStateAsync(::std::function<void(::RoboCompGenericBase::TBaseState)> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompGenericBase::TBaseState>(response, ex, sent, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_getBaseState, context);
    }

    void _iceI_getBaseState(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompGenericBase::TBaseState>>&, const ::Ice::Context&);

    void resetOdometer(const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_resetOdometer, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto resetOdometerAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_resetOdometer, context);
    }

    ::std::function<void()>
    resetOdometerAsync(::std::function<void()> response,
                       ::std::function<void(::std::exception_ptr)> ex = nullptr,
                       ::std::function<void(bool)> sent = nullptr,
                       const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_resetOdometer, context);
    }

    void _iceI_resetOdometer(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::Ice::Context&);

    void setOdometer(const ::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_setOdometer, iceP_state, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto setOdometerAsync(const ::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_setOdometer, iceP_state, context);
    }

    ::std::function<void()>
    setOdometerAsync(const ::RoboCompGenericBase::TBaseState& iceP_state,
                     ::std::function<void()> response,
                     ::std::function<void(::std::exception_ptr)> ex = nullptr,
                     ::std::function<void(bool)> sent = nullptr,
                     const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_setOdometer, iceP_state, context);
    }

    void _iceI_setOdometer(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::RoboCompGenericBase::TBaseState&, const ::Ice::Context&);

    void setOdometerPose(int iceP_x, int iceP_z, float iceP_alpha, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_setOdometerPose, iceP_x, iceP_z, iceP_alpha, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto setOdometerPoseAsync(int iceP_x, int iceP_z, float iceP_alpha, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_setOdometerPose, iceP_x, iceP_z, iceP_alpha, context);
    }

    ::std::function<void()>
    setOdometerPoseAsync(int iceP_x, int iceP_z, float iceP_alpha,
                         ::std::function<void()> response,
                         ::std::function<void(::std::exception_ptr)> ex = nullptr,
                         ::std::function<void(bool)> sent = nullptr,
                         const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_setOdometerPose, iceP_x, iceP_z, iceP_alpha, context);
    }

    void _iceI_setOdometerPose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, int, int, float, const ::Ice::Context&);

    void setSpeedBase(float iceP_advx, float iceP_advz, float iceP_rot, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_setSpeedBase, iceP_advx, iceP_advz, iceP_rot, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto setSpeedBaseAsync(float iceP_advx, float iceP_advz, float iceP_rot, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_setSpeedBase, iceP_advx, iceP_advz, iceP_rot, context);
    }

    ::std::function<void()>
    setSpeedBaseAsync(float iceP_advx, float iceP_advz, float iceP_rot,
                      ::std::function<void()> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_setSpeedBase, iceP_advx, iceP_advz, iceP_rot, context);
    }

    void _iceI_setSpeedBase(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, float, float, float, const ::Ice::Context&);

    void stopBase(const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_stopBase, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto stopBaseAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_stopBase, context);
    }

    ::std::function<void()>
    stopBaseAsync(::std::function<void()> response,
                  ::std::function<void(::std::exception_ptr)> ex = nullptr,
                  ::std::function<void(bool)> sent = nullptr,
                  const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompOmniRobot::OmniRobotPrx::_iceI_stopBase, context);
    }

    void _iceI_stopBase(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::Ice::Context&);

    static const ::std::string& ice_staticId();

protected:

    OmniRobotPrx() = default;
    friend ::std::shared_ptr<OmniRobotPrx> IceInternal::createProxy<OmniRobotPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
};

}

namespace Ice
{

template<>
struct StreamableTraits<::RoboCompOmniRobot::TMechParams>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 14;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompOmniRobot::TMechParams, S>
{
    static void read(S* istr, ::RoboCompOmniRobot::TMechParams& v)
    {
        istr->readAll(v.temp, v.device, v.handler, v.maxVelAdv, v.maxVelRot);
    }
};

}

namespace RoboCompOmniRobot
{

using OmniRobotPtr = ::std::shared_ptr<OmniRobot>;
using OmniRobotPrxPtr = ::std::shared_ptr<OmniRobotPrx>;

}

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompOmniRobot
{

class OmniRobot;
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompOmniRobot::OmniRobot>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompOmniRobot::OmniRobot*);

}

}

namespace RoboCompOmniRobot
{

class OmniRobot;
::Ice::Object* upCast(::RoboCompOmniRobot::OmniRobot*);
typedef ::IceInternal::Handle< ::RoboCompOmniRobot::OmniRobot> OmniRobotPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompOmniRobot::OmniRobot> OmniRobotPrx;
typedef OmniRobotPrx OmniRobotPrxPtr;
void _icePatchObjectPtr(OmniRobotPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompOmniRobot
{

struct TMechParams
{
    ::Ice::Float temp;
    ::std::string device;
    ::std::string handler;
    ::Ice::Float maxVelAdv;
    ::Ice::Float maxVelRot;
};

}

namespace RoboCompOmniRobot
{

class Callback_OmniRobot_correctOdometer_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_OmniRobot_correctOdometer_Base> Callback_OmniRobot_correctOdometerPtr;

class Callback_OmniRobot_getBasePose_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_OmniRobot_getBasePose_Base> Callback_OmniRobot_getBasePosePtr;

class Callback_OmniRobot_getBaseState_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_OmniRobot_getBaseState_Base> Callback_OmniRobot_getBaseStatePtr;

class Callback_OmniRobot_resetOdometer_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_OmniRobot_resetOdometer_Base> Callback_OmniRobot_resetOdometerPtr;

class Callback_OmniRobot_setOdometer_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_OmniRobot_setOdometer_Base> Callback_OmniRobot_setOdometerPtr;

class Callback_OmniRobot_setOdometerPose_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_OmniRobot_setOdometerPose_Base> Callback_OmniRobot_setOdometerPosePtr;

class Callback_OmniRobot_setSpeedBase_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_OmniRobot_setSpeedBase_Base> Callback_OmniRobot_setSpeedBasePtr;

class Callback_OmniRobot_stopBase_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_OmniRobot_stopBase_Base> Callback_OmniRobot_stopBasePtr;

}

namespace IceProxy
{

namespace RoboCompOmniRobot
{

class OmniRobot : public virtual ::Ice::Proxy<OmniRobot, ::IceProxy::Ice::Object>
{
public:

    void correctOdometer(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_correctOdometer(_iceI_begin_correctOdometer(iceP_x, iceP_z, iceP_alpha, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_correctOdometer(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_correctOdometer(iceP_x, iceP_z, iceP_alpha, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_correctOdometer(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_correctOdometer(iceP_x, iceP_z, iceP_alpha, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_correctOdometer(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_correctOdometer(iceP_x, iceP_z, iceP_alpha, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_correctOdometer(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::RoboCompOmniRobot::Callback_OmniRobot_correctOdometerPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_correctOdometer(iceP_x, iceP_z, iceP_alpha, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_correctOdometer(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::Ice::Context& context, const ::RoboCompOmniRobot::Callback_OmniRobot_correctOdometerPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_correctOdometer(iceP_x, iceP_z, iceP_alpha, context, del, cookie);
    }

    void end_correctOdometer(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_correctOdometer(::Ice::Int, ::Ice::Int, ::Ice::Float, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void getBasePose(::Ice::Int& iceP_x, ::Ice::Int& iceP_z, ::Ice::Float& iceP_alpha, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_getBasePose(iceP_x, iceP_z, iceP_alpha, _iceI_begin_getBasePose(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getBasePose(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getBasePose(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getBasePose(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBasePose(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBasePose(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBasePose(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBasePose(const ::RoboCompOmniRobot::Callback_OmniRobot_getBasePosePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBasePose(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBasePose(const ::Ice::Context& context, const ::RoboCompOmniRobot::Callback_OmniRobot_getBasePosePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBasePose(context, del, cookie);
    }

    void end_getBasePose(::Ice::Int& iceP_x, ::Ice::Int& iceP_z, ::Ice::Float& iceP_alpha, const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getBasePose(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void getBaseState(::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_getBaseState(iceP_state, _iceI_begin_getBaseState(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getBaseState(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getBaseState(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getBaseState(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBaseState(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBaseState(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBaseState(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBaseState(const ::RoboCompOmniRobot::Callback_OmniRobot_getBaseStatePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBaseState(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBaseState(const ::Ice::Context& context, const ::RoboCompOmniRobot::Callback_OmniRobot_getBaseStatePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBaseState(context, del, cookie);
    }

    void end_getBaseState(::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getBaseState(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void resetOdometer(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_resetOdometer(_iceI_begin_resetOdometer(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_resetOdometer(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_resetOdometer(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_resetOdometer(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_resetOdometer(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_resetOdometer(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_resetOdometer(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_resetOdometer(const ::RoboCompOmniRobot::Callback_OmniRobot_resetOdometerPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_resetOdometer(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_resetOdometer(const ::Ice::Context& context, const ::RoboCompOmniRobot::Callback_OmniRobot_resetOdometerPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_resetOdometer(context, del, cookie);
    }

    void end_resetOdometer(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_resetOdometer(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void setOdometer(const ::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_setOdometer(_iceI_begin_setOdometer(iceP_state, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_setOdometer(const ::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_setOdometer(iceP_state, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setOdometer(const ::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setOdometer(iceP_state, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setOdometer(const ::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setOdometer(iceP_state, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setOdometer(const ::RoboCompGenericBase::TBaseState& iceP_state, const ::RoboCompOmniRobot::Callback_OmniRobot_setOdometerPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setOdometer(iceP_state, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setOdometer(const ::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::Context& context, const ::RoboCompOmniRobot::Callback_OmniRobot_setOdometerPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setOdometer(iceP_state, context, del, cookie);
    }

    void end_setOdometer(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_setOdometer(const ::RoboCompGenericBase::TBaseState&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void setOdometerPose(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_setOdometerPose(_iceI_begin_setOdometerPose(iceP_x, iceP_z, iceP_alpha, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_setOdometerPose(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_setOdometerPose(iceP_x, iceP_z, iceP_alpha, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setOdometerPose(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setOdometerPose(iceP_x, iceP_z, iceP_alpha, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setOdometerPose(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setOdometerPose(iceP_x, iceP_z, iceP_alpha, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setOdometerPose(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::RoboCompOmniRobot::Callback_OmniRobot_setOdometerPosePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setOdometerPose(iceP_x, iceP_z, iceP_alpha, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setOdometerPose(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::Ice::Context& context, const ::RoboCompOmniRobot::Callback_OmniRobot_setOdometerPosePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setOdometerPose(iceP_x, iceP_z, iceP_alpha, context, del, cookie);
    }

    void end_setOdometerPose(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_setOdometerPose(::Ice::Int, ::Ice::Int, ::Ice::Float, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void setSpeedBase(::Ice::Float iceP_advx, ::Ice::Float iceP_advz, ::Ice::Float iceP_rot, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_setSpeedBase(_iceI_begin_setSpeedBase(iceP_advx, iceP_advz, iceP_rot, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_setSpeedBase(::Ice::Float iceP_advx, ::Ice::Float iceP_advz, ::Ice::Float iceP_rot, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_setSpeedBase(iceP_advx, iceP_advz, iceP_rot, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setSpeedBase(::Ice::Float iceP_advx, ::Ice::Float iceP_advz, ::Ice::Float iceP_rot, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setSpeedBase(iceP_advx, iceP_advz, iceP_rot, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setSpeedBase(::Ice::Float iceP_advx, ::Ice::Float iceP_advz, ::Ice::Float iceP_rot, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setSpeedBase(iceP_advx, iceP_advz, iceP_rot, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setSpeedBase(::Ice::Float iceP_advx, ::Ice::Float iceP_advz, ::Ice::Float iceP_rot, const ::RoboCompOmniRobot::Callback_OmniRobot_setSpeedBasePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setSpeedBase(iceP_advx, iceP_advz, iceP_rot, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setSpeedBase(::Ice::Float iceP_advx, ::Ice::Float iceP_advz, ::Ice::Float iceP_rot, const ::Ice::Context& context, const ::RoboCompOmniRobot::Callback_OmniRobot_setSpeedBasePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setSpeedBase(iceP_advx, iceP_advz, iceP_rot, context, del, cookie);
    }

    void end_setSpeedBase(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_setSpeedBase(::Ice::Float, ::Ice::Float, ::Ice::Float, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void stopBase(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_stopBase(_iceI_begin_stopBase(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_stopBase(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_stopBase(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_stopBase(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_stopBase(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_stopBase(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_stopBase(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_stopBase(const ::RoboCompOmniRobot::Callback_OmniRobot_stopBasePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_stopBase(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_stopBase(const ::Ice::Context& context, const ::RoboCompOmniRobot::Callback_OmniRobot_stopBasePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_stopBase(context, del, cookie);
    }

    void end_stopBase(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_stopBase(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    static const ::std::string& ice_staticId();

protected:

    virtual ::IceProxy::Ice::Object* _newInstance() const;
};

}

}

namespace RoboCompOmniRobot
{

class OmniRobot : public virtual ::Ice::Object
{
public:

    typedef OmniRobotPrx ProxyType;
    typedef OmniRobotPtr PointerType;

    virtual ~OmniRobot();

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::emptyCurrent) const;

    static const ::std::string& ice_staticId();

    virtual void correctOdometer(::Ice::Int, ::Ice::Int, ::Ice::Float, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_correctOdometer(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void getBasePose(::Ice::Int&, ::Ice::Int&, ::Ice::Float&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_getBasePose(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void getBaseState(::RoboCompGenericBase::TBaseState&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_getBaseState(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void resetOdometer(const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_resetOdometer(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setOdometer(const ::RoboCompGenericBase::TBaseState&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_setOdometer(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setOdometerPose(::Ice::Int, ::Ice::Int, ::Ice::Float, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_setOdometerPose(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setSpeedBase(::Ice::Float, ::Ice::Float, ::Ice::Float, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_setSpeedBase(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void stopBase(const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_stopBase(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:

    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
};

inline bool operator==(const OmniRobot& lhs, const OmniRobot& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const OmniRobot& lhs, const OmniRobot& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}

}

namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompOmniRobot::TMechParams>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 14;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompOmniRobot::TMechParams, S>
{
    static void write(S* ostr, const ::RoboCompOmniRobot::TMechParams& v)
    {
        ostr->write(v.temp);
        ostr->write(v.device);
        ostr->write(v.handler);
        ostr->write(v.maxVelAdv);
        ostr->write(v.maxVelRot);
    }
};

template<typename S>
struct StreamReader< ::RoboCompOmniRobot::TMechParams, S>
{
    static void read(S* istr, ::RoboCompOmniRobot::TMechParams& v)
    {
        istr->read(v.temp);
        istr->read(v.device);
        istr->read(v.handler);
        istr->read(v.maxVelAdv);
        istr->read(v.maxVelRot);
    }
};

}

namespace RoboCompOmniRobot
{

template<class T>
class CallbackNC_OmniRobot_correctOdometer : public Callback_OmniRobot_correctOdometer_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_OmniRobot_correctOdometer(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_correctOdometer(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)();
        }
    }

private:

    Response _response;
};

template<class T> Callback_OmniRobot_correctOdometerPtr
newCallback_OmniRobot_correctOdometer(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_correctOdometer<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_correctOdometerPtr
newCallback_OmniRobot_correctOdometer(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_correctOdometer<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_OmniRobot_correctOdometerPtr
newCallback_OmniRobot_correctOdometer(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_correctOdometer<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_correctOdometerPtr
newCallback_OmniRobot_correctOdometer(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_correctOdometer<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_OmniRobot_correctOdometer : public Callback_OmniRobot_correctOdometer_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_OmniRobot_correctOdometer(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_correctOdometer(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_OmniRobot_correctOdometerPtr
newCallback_OmniRobot_correctOdometer(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_correctOdometer<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_correctOdometerPtr
newCallback_OmniRobot_correctOdometer(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_correctOdometer<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_correctOdometerPtr
newCallback_OmniRobot_correctOdometer(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_correctOdometer<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_correctOdometerPtr
newCallback_OmniRobot_correctOdometer(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_correctOdometer<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_OmniRobot_getBasePose : public Callback_OmniRobot_getBasePose_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int, ::Ice::Int, ::Ice::Float);

    CallbackNC_OmniRobot_getBasePose(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        ::Ice::Int iceP_x;
        ::Ice::Int iceP_z;
        ::Ice::Float iceP_alpha;
        try
        {
            proxy->end_getBasePose(iceP_x, iceP_z, iceP_alpha, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(iceP_x, iceP_z, iceP_alpha);
        }
    }

private:

    Response _response;
};

template<class T> Callback_OmniRobot_getBasePosePtr
newCallback_OmniRobot_getBasePose(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, ::Ice::Int, ::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_getBasePose<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_getBasePosePtr
newCallback_OmniRobot_getBasePose(T* instance, void (T::*cb)(::Ice::Int, ::Ice::Int, ::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_getBasePose<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_OmniRobot_getBasePose : public Callback_OmniRobot_getBasePose_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, ::Ice::Int, ::Ice::Float, const CT&);

    Callback_OmniRobot_getBasePose(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        ::Ice::Int iceP_x;
        ::Ice::Int iceP_z;
        ::Ice::Float iceP_alpha;
        try
        {
            proxy->end_getBasePose(iceP_x, iceP_z, iceP_alpha, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(iceP_x, iceP_z, iceP_alpha, CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_OmniRobot_getBasePosePtr
newCallback_OmniRobot_getBasePose(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, ::Ice::Int, ::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_getBasePose<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_getBasePosePtr
newCallback_OmniRobot_getBasePose(T* instance, void (T::*cb)(::Ice::Int, ::Ice::Int, ::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_getBasePose<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_OmniRobot_getBaseState : public Callback_OmniRobot_getBaseState_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::RoboCompGenericBase::TBaseState&);

    CallbackNC_OmniRobot_getBaseState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        ::RoboCompGenericBase::TBaseState iceP_state;
        try
        {
            proxy->end_getBaseState(iceP_state, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(iceP_state);
        }
    }

private:

    Response _response;
};

template<class T> Callback_OmniRobot_getBaseStatePtr
newCallback_OmniRobot_getBaseState(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::RoboCompGenericBase::TBaseState&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_getBaseState<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_getBaseStatePtr
newCallback_OmniRobot_getBaseState(T* instance, void (T::*cb)(const ::RoboCompGenericBase::TBaseState&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_getBaseState<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_OmniRobot_getBaseState : public Callback_OmniRobot_getBaseState_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::RoboCompGenericBase::TBaseState&, const CT&);

    Callback_OmniRobot_getBaseState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        ::RoboCompGenericBase::TBaseState iceP_state;
        try
        {
            proxy->end_getBaseState(iceP_state, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(iceP_state, CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_OmniRobot_getBaseStatePtr
newCallback_OmniRobot_getBaseState(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::RoboCompGenericBase::TBaseState&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_getBaseState<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_getBaseStatePtr
newCallback_OmniRobot_getBaseState(T* instance, void (T::*cb)(const ::RoboCompGenericBase::TBaseState&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_getBaseState<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_OmniRobot_resetOdometer : public Callback_OmniRobot_resetOdometer_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_OmniRobot_resetOdometer(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_resetOdometer(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)();
        }
    }

private:

    Response _response;
};

template<class T> Callback_OmniRobot_resetOdometerPtr
newCallback_OmniRobot_resetOdometer(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_resetOdometer<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_resetOdometerPtr
newCallback_OmniRobot_resetOdometer(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_resetOdometer<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_OmniRobot_resetOdometerPtr
newCallback_OmniRobot_resetOdometer(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_resetOdometer<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_resetOdometerPtr
newCallback_OmniRobot_resetOdometer(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_resetOdometer<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_OmniRobot_resetOdometer : public Callback_OmniRobot_resetOdometer_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_OmniRobot_resetOdometer(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_resetOdometer(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_OmniRobot_resetOdometerPtr
newCallback_OmniRobot_resetOdometer(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_resetOdometer<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_resetOdometerPtr
newCallback_OmniRobot_resetOdometer(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_resetOdometer<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_resetOdometerPtr
newCallback_OmniRobot_resetOdometer(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_resetOdometer<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_resetOdometerPtr
newCallback_OmniRobot_resetOdometer(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_resetOdometer<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_OmniRobot_setOdometer : public Callback_OmniRobot_setOdometer_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_OmniRobot_setOdometer(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_setOdometer(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)();
        }
    }

private:

    Response _response;
};

template<class T> Callback_OmniRobot_setOdometerPtr
newCallback_OmniRobot_setOdometer(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_setOdometer<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_setOdometerPtr
newCallback_OmniRobot_setOdometer(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_setOdometer<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_OmniRobot_setOdometerPtr
newCallback_OmniRobot_setOdometer(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_setOdometer<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_setOdometerPtr
newCallback_OmniRobot_setOdometer(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_setOdometer<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_OmniRobot_setOdometer : public Callback_OmniRobot_setOdometer_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_OmniRobot_setOdometer(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_setOdometer(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_OmniRobot_setOdometerPtr
newCallback_OmniRobot_setOdometer(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_setOdometer<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_setOdometerPtr
newCallback_OmniRobot_setOdometer(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_setOdometer<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_setOdometerPtr
newCallback_OmniRobot_setOdometer(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_setOdometer<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_setOdometerPtr
newCallback_OmniRobot_setOdometer(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_setOdometer<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_OmniRobot_setOdometerPose : public Callback_OmniRobot_setOdometerPose_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_OmniRobot_setOdometerPose(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_setOdometerPose(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)();
        }
    }

private:

    Response _response;
};

template<class T> Callback_OmniRobot_setOdometerPosePtr
newCallback_OmniRobot_setOdometerPose(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_setOdometerPose<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_setOdometerPosePtr
newCallback_OmniRobot_setOdometerPose(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_setOdometerPose<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_OmniRobot_setOdometerPosePtr
newCallback_OmniRobot_setOdometerPose(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_setOdometerPose<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_setOdometerPosePtr
newCallback_OmniRobot_setOdometerPose(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_setOdometerPose<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_OmniRobot_setOdometerPose : public Callback_OmniRobot_setOdometerPose_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_OmniRobot_setOdometerPose(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_setOdometerPose(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_OmniRobot_setOdometerPosePtr
newCallback_OmniRobot_setOdometerPose(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_setOdometerPose<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_setOdometerPosePtr
newCallback_OmniRobot_setOdometerPose(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_setOdometerPose<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_setOdometerPosePtr
newCallback_OmniRobot_setOdometerPose(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_setOdometerPose<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_setOdometerPosePtr
newCallback_OmniRobot_setOdometerPose(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_setOdometerPose<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_OmniRobot_setSpeedBase : public Callback_OmniRobot_setSpeedBase_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_OmniRobot_setSpeedBase(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_setSpeedBase(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)();
        }
    }

private:

    Response _response;
};

template<class T> Callback_OmniRobot_setSpeedBasePtr
newCallback_OmniRobot_setSpeedBase(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_setSpeedBase<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_setSpeedBasePtr
newCallback_OmniRobot_setSpeedBase(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_setSpeedBase<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_OmniRobot_setSpeedBasePtr
newCallback_OmniRobot_setSpeedBase(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_setSpeedBase<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_setSpeedBasePtr
newCallback_OmniRobot_setSpeedBase(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_setSpeedBase<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_OmniRobot_setSpeedBase : public Callback_OmniRobot_setSpeedBase_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_OmniRobot_setSpeedBase(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_setSpeedBase(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_OmniRobot_setSpeedBasePtr
newCallback_OmniRobot_setSpeedBase(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_setSpeedBase<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_setSpeedBasePtr
newCallback_OmniRobot_setSpeedBase(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_setSpeedBase<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_setSpeedBasePtr
newCallback_OmniRobot_setSpeedBase(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_setSpeedBase<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_setSpeedBasePtr
newCallback_OmniRobot_setSpeedBase(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_setSpeedBase<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_OmniRobot_stopBase : public Callback_OmniRobot_stopBase_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_OmniRobot_stopBase(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_stopBase(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)();
        }
    }

private:

    Response _response;
};

template<class T> Callback_OmniRobot_stopBasePtr
newCallback_OmniRobot_stopBase(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_stopBase<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_stopBasePtr
newCallback_OmniRobot_stopBase(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_stopBase<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_OmniRobot_stopBasePtr
newCallback_OmniRobot_stopBase(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_stopBase<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_OmniRobot_stopBasePtr
newCallback_OmniRobot_stopBase(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_OmniRobot_stopBase<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_OmniRobot_stopBase : public Callback_OmniRobot_stopBase_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_OmniRobot_stopBase(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompOmniRobot::OmniRobotPrx proxy = ::RoboCompOmniRobot::OmniRobotPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_stopBase(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_OmniRobot_stopBasePtr
newCallback_OmniRobot_stopBase(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_stopBase<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_stopBasePtr
newCallback_OmniRobot_stopBase(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_stopBase<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_stopBasePtr
newCallback_OmniRobot_stopBase(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_stopBase<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_OmniRobot_stopBasePtr
newCallback_OmniRobot_stopBase(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_OmniRobot_stopBase<T, CT>(instance, 0, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
