// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `PeopleDetector.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <PeopleDetector.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompPeopleDetector_PeopleDetector_ids[2] =
{
    "::Ice::Object",
    "::RoboCompPeopleDetector::PeopleDetector"
};
const ::std::string iceC_RoboCompPeopleDetector_PeopleDetector_ops[] =
{
    "gotpeople",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompPeopleDetector_PeopleDetector_gotpeople_name = "gotpeople";

}

bool
RoboCompPeopleDetector::PeopleDetector::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompPeopleDetector_PeopleDetector_ids, iceC_RoboCompPeopleDetector_PeopleDetector_ids + 2, s);
}

::std::vector<::std::string>
RoboCompPeopleDetector::PeopleDetector::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompPeopleDetector_PeopleDetector_ids[0], &iceC_RoboCompPeopleDetector_PeopleDetector_ids[2]);
}

::std::string
RoboCompPeopleDetector::PeopleDetector::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompPeopleDetector::PeopleDetector::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompPeopleDetector::PeopleDetector";
    return typeId;
}

bool
RoboCompPeopleDetector::PeopleDetector::_iceD_gotpeople(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompPeopleDetector::PeopleList iceP_lst;
    istr->readAll(iceP_lst);
    inS.endReadParams();
    this->gotpeople(::std::move(iceP_lst), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompPeopleDetector::PeopleDetector::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompPeopleDetector_PeopleDetector_ops, iceC_RoboCompPeopleDetector_PeopleDetector_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompPeopleDetector_PeopleDetector_ops)
    {
        case 0:
        {
            return _iceD_gotpeople(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompPeopleDetector::PeopleDetectorPrx::_iceI_gotpeople(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompPeopleDetector::PeopleList& iceP_lst, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompPeopleDetector_PeopleDetector_gotpeople_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_lst);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
RoboCompPeopleDetector::PeopleDetectorPrx::_newInstance() const
{
    return ::IceInternal::createProxy<PeopleDetectorPrx>();
}

const ::std::string&
RoboCompPeopleDetector::PeopleDetectorPrx::ice_staticId()
{
    return RoboCompPeopleDetector::PeopleDetector::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompPeopleDetector_PeopleDetector_gotpeople_name = "gotpeople";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompPeopleDetector::upCast(::IceProxy::RoboCompPeopleDetector::PeopleDetector* p) { return p; }

void
::IceProxy::RoboCompPeopleDetector::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompPeopleDetector::PeopleDetector>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompPeopleDetector::PeopleDetector;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompPeopleDetector::PeopleDetector::_iceI_begin_gotpeople(const ::RoboCompPeopleDetector::PeopleList& iceP_lst, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompPeopleDetector_PeopleDetector_gotpeople_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompPeopleDetector_PeopleDetector_gotpeople_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_lst);
        result->endWriteParams();
        result->invoke(iceC_RoboCompPeopleDetector_PeopleDetector_gotpeople_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompPeopleDetector::PeopleDetector::end_gotpeople(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompPeopleDetector_PeopleDetector_gotpeople_name);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompPeopleDetector::PeopleDetector::_newInstance() const
{
    return new PeopleDetector;
}

const ::std::string&
IceProxy::RoboCompPeopleDetector::PeopleDetector::ice_staticId()
{
    return ::RoboCompPeopleDetector::PeopleDetector::ice_staticId();
}

RoboCompPeopleDetector::PeopleDetector::~PeopleDetector()
{
}

::Ice::Object* RoboCompPeopleDetector::upCast(::RoboCompPeopleDetector::PeopleDetector* p) { return p; }


namespace
{
const ::std::string iceC_RoboCompPeopleDetector_PeopleDetector_ids[2] =
{
    "::Ice::Object",
    "::RoboCompPeopleDetector::PeopleDetector"
};

}

bool
RoboCompPeopleDetector::PeopleDetector::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompPeopleDetector_PeopleDetector_ids, iceC_RoboCompPeopleDetector_PeopleDetector_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompPeopleDetector::PeopleDetector::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompPeopleDetector_PeopleDetector_ids[0], &iceC_RoboCompPeopleDetector_PeopleDetector_ids[2]);
}

const ::std::string&
RoboCompPeopleDetector::PeopleDetector::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompPeopleDetector::PeopleDetector::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompPeopleDetector::PeopleDetector";
    return typeId;
#else
    return iceC_RoboCompPeopleDetector_PeopleDetector_ids[1];
#endif
}

bool
RoboCompPeopleDetector::PeopleDetector::_iceD_gotpeople(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompPeopleDetector::PeopleList iceP_lst;
    istr->read(iceP_lst);
    inS.endReadParams();
    this->gotpeople(iceP_lst, current);
    inS.writeEmptyParams();
    return true;
}

namespace
{
const ::std::string iceC_RoboCompPeopleDetector_PeopleDetector_all[] =
{
    "gotpeople",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

bool
RoboCompPeopleDetector::PeopleDetector::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompPeopleDetector_PeopleDetector_all, iceC_RoboCompPeopleDetector_PeopleDetector_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompPeopleDetector_PeopleDetector_all)
    {
        case 0:
        {
            return _iceD_gotpeople(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompPeopleDetector::PeopleDetector::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::RoboCompPeopleDetector::PeopleDetector, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompPeopleDetector::PeopleDetector::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::RoboCompPeopleDetector::PeopleDetector, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
RoboCompPeopleDetector::_icePatchObjectPtr(PeopleDetectorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompPeopleDetector::PeopleDetectorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompPeopleDetector::PeopleDetector::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
