// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Simulator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Simulator_h__
#define __Simulator_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompSimulator
{

class Simulator;
class SimulatorPrx;

}

namespace RoboCompSimulator
{

class Simulator : public virtual ::Ice::Object
{
public:

    using ProxyType = SimulatorPrx;

    virtual bool ice_isA(::std::string, const ::Ice::Current&) const override;
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current&) const override;
    virtual ::std::string ice_id(const ::Ice::Current&) const override;

    static const ::std::string& ice_staticId();

    virtual void regenerate(::std::string, const ::Ice::Current&) = 0;
    bool _iceD_regenerate(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void step(int, const ::Ice::Current&) = 0;
    bool _iceD_step(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
};

}

namespace RoboCompSimulator
{

class SimulatorPrx : public virtual ::Ice::Proxy<SimulatorPrx, ::Ice::ObjectPrx>
{
public:

    void regenerate(const ::std::string& iceP_scene, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompSimulator::SimulatorPrx::_iceI_regenerate, iceP_scene, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto regenerateAsync(const ::std::string& iceP_scene, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompSimulator::SimulatorPrx::_iceI_regenerate, iceP_scene, context);
    }

    ::std::function<void()>
    regenerateAsync(const ::std::string& iceP_scene,
                    ::std::function<void()> response,
                    ::std::function<void(::std::exception_ptr)> ex = nullptr,
                    ::std::function<void(bool)> sent = nullptr,
                    const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompSimulator::SimulatorPrx::_iceI_regenerate, iceP_scene, context);
    }

    void _iceI_regenerate(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::std::string&, const ::Ice::Context&);

    void step(int iceP_timestep, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompSimulator::SimulatorPrx::_iceI_step, iceP_timestep, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto stepAsync(int iceP_timestep, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompSimulator::SimulatorPrx::_iceI_step, iceP_timestep, context);
    }

    ::std::function<void()>
    stepAsync(int iceP_timestep,
              ::std::function<void()> response,
              ::std::function<void(::std::exception_ptr)> ex = nullptr,
              ::std::function<void(bool)> sent = nullptr,
              const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompSimulator::SimulatorPrx::_iceI_step, iceP_timestep, context);
    }

    void _iceI_step(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, int, const ::Ice::Context&);

    static const ::std::string& ice_staticId();

protected:

    SimulatorPrx() = default;
    friend ::std::shared_ptr<SimulatorPrx> IceInternal::createProxy<SimulatorPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
};

}

namespace Ice
{

}

namespace RoboCompSimulator
{

using SimulatorPtr = ::std::shared_ptr<Simulator>;
using SimulatorPrxPtr = ::std::shared_ptr<SimulatorPrx>;

}

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompSimulator
{

class Simulator;
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompSimulator::Simulator>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompSimulator::Simulator*);

}

}

namespace RoboCompSimulator
{

class Simulator;
::Ice::Object* upCast(::RoboCompSimulator::Simulator*);
typedef ::IceInternal::Handle< ::RoboCompSimulator::Simulator> SimulatorPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompSimulator::Simulator> SimulatorPrx;
typedef SimulatorPrx SimulatorPrxPtr;
void _icePatchObjectPtr(SimulatorPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompSimulator
{

class Callback_Simulator_regenerate_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Simulator_regenerate_Base> Callback_Simulator_regeneratePtr;

class Callback_Simulator_step_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Simulator_step_Base> Callback_Simulator_stepPtr;

}

namespace IceProxy
{

namespace RoboCompSimulator
{

class Simulator : public virtual ::Ice::Proxy<Simulator, ::IceProxy::Ice::Object>
{
public:

    void regenerate(const ::std::string& iceP_scene, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_regenerate(_iceI_begin_regenerate(iceP_scene, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_regenerate(const ::std::string& iceP_scene, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_regenerate(iceP_scene, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_regenerate(const ::std::string& iceP_scene, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_regenerate(iceP_scene, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_regenerate(const ::std::string& iceP_scene, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_regenerate(iceP_scene, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_regenerate(const ::std::string& iceP_scene, const ::RoboCompSimulator::Callback_Simulator_regeneratePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_regenerate(iceP_scene, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_regenerate(const ::std::string& iceP_scene, const ::Ice::Context& context, const ::RoboCompSimulator::Callback_Simulator_regeneratePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_regenerate(iceP_scene, context, del, cookie);
    }

    void end_regenerate(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_regenerate(const ::std::string&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void step(::Ice::Int iceP_timestep, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_step(_iceI_begin_step(iceP_timestep, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_step(::Ice::Int iceP_timestep, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_step(iceP_timestep, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_step(::Ice::Int iceP_timestep, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_step(iceP_timestep, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_step(::Ice::Int iceP_timestep, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_step(iceP_timestep, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_step(::Ice::Int iceP_timestep, const ::RoboCompSimulator::Callback_Simulator_stepPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_step(iceP_timestep, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_step(::Ice::Int iceP_timestep, const ::Ice::Context& context, const ::RoboCompSimulator::Callback_Simulator_stepPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_step(iceP_timestep, context, del, cookie);
    }

    void end_step(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_step(::Ice::Int, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    static const ::std::string& ice_staticId();

protected:

    virtual ::IceProxy::Ice::Object* _newInstance() const;
};

}

}

namespace RoboCompSimulator
{

class Simulator : public virtual ::Ice::Object
{
public:

    typedef SimulatorPrx ProxyType;
    typedef SimulatorPtr PointerType;

    virtual ~Simulator();

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::emptyCurrent) const;

    static const ::std::string& ice_staticId();

    virtual void regenerate(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_regenerate(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void step(::Ice::Int, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_step(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:

    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
};

inline bool operator==(const Simulator& lhs, const Simulator& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const Simulator& lhs, const Simulator& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}

}

namespace Ice
{

}

namespace RoboCompSimulator
{

template<class T>
class CallbackNC_Simulator_regenerate : public Callback_Simulator_regenerate_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Simulator_regenerate(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Simulator_regeneratePtr
newCallback_Simulator_regenerate(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Simulator_regenerate<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Simulator_regeneratePtr
newCallback_Simulator_regenerate(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Simulator_regenerate<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Simulator_regeneratePtr
newCallback_Simulator_regenerate(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Simulator_regenerate<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Simulator_regeneratePtr
newCallback_Simulator_regenerate(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Simulator_regenerate<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Simulator_regenerate : public Callback_Simulator_regenerate_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Simulator_regenerate(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Simulator_regeneratePtr
newCallback_Simulator_regenerate(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Simulator_regenerate<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Simulator_regeneratePtr
newCallback_Simulator_regenerate(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Simulator_regenerate<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Simulator_regeneratePtr
newCallback_Simulator_regenerate(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Simulator_regenerate<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Simulator_regeneratePtr
newCallback_Simulator_regenerate(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Simulator_regenerate<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Simulator_step : public Callback_Simulator_step_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Simulator_step(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Simulator_stepPtr
newCallback_Simulator_step(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Simulator_step<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Simulator_stepPtr
newCallback_Simulator_step(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Simulator_step<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Simulator_stepPtr
newCallback_Simulator_step(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Simulator_step<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Simulator_stepPtr
newCallback_Simulator_step(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Simulator_step<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Simulator_step : public Callback_Simulator_step_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Simulator_step(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Simulator_stepPtr
newCallback_Simulator_step(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Simulator_step<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Simulator_stepPtr
newCallback_Simulator_step(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Simulator_step<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Simulator_stepPtr
newCallback_Simulator_step(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Simulator_step<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Simulator_stepPtr
newCallback_Simulator_step(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Simulator_step<T, CT>(instance, 0, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
