// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Simulator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Simulator.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompSimulator_Simulator_ids[2] =
{
    "::Ice::Object",
    "::RoboCompSimulator::Simulator"
};
const ::std::string iceC_RoboCompSimulator_Simulator_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "regenerate",
    "step"
};
const ::std::string iceC_RoboCompSimulator_Simulator_regenerate_name = "regenerate";
const ::std::string iceC_RoboCompSimulator_Simulator_step_name = "step";

}

bool
RoboCompSimulator::Simulator::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompSimulator_Simulator_ids, iceC_RoboCompSimulator_Simulator_ids + 2, s);
}

::std::vector<::std::string>
RoboCompSimulator::Simulator::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompSimulator_Simulator_ids[0], &iceC_RoboCompSimulator_Simulator_ids[2]);
}

::std::string
RoboCompSimulator::Simulator::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompSimulator::Simulator::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompSimulator::Simulator";
    return typeId;
}

bool
RoboCompSimulator::Simulator::_iceD_regenerate(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_scene;
    istr->readAll(iceP_scene);
    inS.endReadParams();
    this->regenerate(::std::move(iceP_scene), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompSimulator::Simulator::_iceD_step(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_timestep;
    istr->readAll(iceP_timestep);
    inS.endReadParams();
    this->step(iceP_timestep, current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompSimulator::Simulator::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompSimulator_Simulator_ops, iceC_RoboCompSimulator_Simulator_ops + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompSimulator_Simulator_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_regenerate(in, current);
        }
        case 5:
        {
            return _iceD_step(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompSimulator::SimulatorPrx::_iceI_regenerate(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_scene, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompSimulator_Simulator_regenerate_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_scene);
        },
        nullptr);
}

void
RoboCompSimulator::SimulatorPrx::_iceI_step(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, int iceP_timestep, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompSimulator_Simulator_step_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_timestep);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
RoboCompSimulator::SimulatorPrx::_newInstance() const
{
    return ::IceInternal::createProxy<SimulatorPrx>();
}

const ::std::string&
RoboCompSimulator::SimulatorPrx::ice_staticId()
{
    return RoboCompSimulator::Simulator::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompSimulator_Simulator_regenerate_name = "regenerate";

const ::std::string iceC_RoboCompSimulator_Simulator_step_name = "step";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompSimulator::upCast(::IceProxy::RoboCompSimulator::Simulator* p) { return p; }

void
::IceProxy::RoboCompSimulator::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompSimulator::Simulator>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompSimulator::Simulator;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompSimulator::Simulator::_iceI_begin_regenerate(const ::std::string& iceP_scene, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompSimulator_Simulator_regenerate_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompSimulator_Simulator_regenerate_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_scene);
        result->endWriteParams();
        result->invoke(iceC_RoboCompSimulator_Simulator_regenerate_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompSimulator::Simulator::end_regenerate(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompSimulator_Simulator_regenerate_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompSimulator::Simulator::_iceI_begin_step(::Ice::Int iceP_timestep, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompSimulator_Simulator_step_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompSimulator_Simulator_step_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_timestep);
        result->endWriteParams();
        result->invoke(iceC_RoboCompSimulator_Simulator_step_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompSimulator::Simulator::end_step(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompSimulator_Simulator_step_name);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompSimulator::Simulator::_newInstance() const
{
    return new Simulator;
}

const ::std::string&
IceProxy::RoboCompSimulator::Simulator::ice_staticId()
{
    return ::RoboCompSimulator::Simulator::ice_staticId();
}

RoboCompSimulator::Simulator::~Simulator()
{
}

::Ice::Object* RoboCompSimulator::upCast(::RoboCompSimulator::Simulator* p) { return p; }


namespace
{
const ::std::string iceC_RoboCompSimulator_Simulator_ids[2] =
{
    "::Ice::Object",
    "::RoboCompSimulator::Simulator"
};

}

bool
RoboCompSimulator::Simulator::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompSimulator_Simulator_ids, iceC_RoboCompSimulator_Simulator_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompSimulator::Simulator::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompSimulator_Simulator_ids[0], &iceC_RoboCompSimulator_Simulator_ids[2]);
}

const ::std::string&
RoboCompSimulator::Simulator::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompSimulator::Simulator::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompSimulator::Simulator";
    return typeId;
#else
    return iceC_RoboCompSimulator_Simulator_ids[1];
#endif
}

bool
RoboCompSimulator::Simulator::_iceD_regenerate(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_scene;
    istr->read(iceP_scene);
    inS.endReadParams();
    this->regenerate(iceP_scene, current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompSimulator::Simulator::_iceD_step(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_timestep;
    istr->read(iceP_timestep);
    inS.endReadParams();
    this->step(iceP_timestep, current);
    inS.writeEmptyParams();
    return true;
}

namespace
{
const ::std::string iceC_RoboCompSimulator_Simulator_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "regenerate",
    "step"
};

}

bool
RoboCompSimulator::Simulator::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompSimulator_Simulator_all, iceC_RoboCompSimulator_Simulator_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompSimulator_Simulator_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_regenerate(in, current);
        }
        case 5:
        {
            return _iceD_step(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompSimulator::Simulator::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::RoboCompSimulator::Simulator, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompSimulator::Simulator::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::RoboCompSimulator::Simulator, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
RoboCompSimulator::_icePatchObjectPtr(SimulatorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompSimulator::SimulatorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompSimulator::Simulator::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
