// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `WallDetector.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <WallDetector.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompWallDetector_WallDetector_ids[2] =
{
    "::Ice::Object",
    "::RoboCompWallDetector::WallDetector"
};
const ::std::string iceC_RoboCompWallDetector_WallDetector_ops[] =
{
    "gotwalls",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompWallDetector_WallDetector_gotwalls_name = "gotwalls";

}

bool
RoboCompWallDetector::WallDetector::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompWallDetector_WallDetector_ids, iceC_RoboCompWallDetector_WallDetector_ids + 2, s);
}

::std::vector<::std::string>
RoboCompWallDetector::WallDetector::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompWallDetector_WallDetector_ids[0], &iceC_RoboCompWallDetector_WallDetector_ids[2]);
}

::std::string
RoboCompWallDetector::WallDetector::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompWallDetector::WallDetector::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompWallDetector::WallDetector";
    return typeId;
}

bool
RoboCompWallDetector::WallDetector::_iceD_gotwalls(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompWallDetector::WallList iceP_lst;
    istr->readAll(iceP_lst);
    inS.endReadParams();
    this->gotwalls(::std::move(iceP_lst), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompWallDetector::WallDetector::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompWallDetector_WallDetector_ops, iceC_RoboCompWallDetector_WallDetector_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompWallDetector_WallDetector_ops)
    {
        case 0:
        {
            return _iceD_gotwalls(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompWallDetector::WallDetectorPrx::_iceI_gotwalls(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompWallDetector::WallList& iceP_lst, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompWallDetector_WallDetector_gotwalls_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_lst);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
RoboCompWallDetector::WallDetectorPrx::_newInstance() const
{
    return ::IceInternal::createProxy<WallDetectorPrx>();
}

const ::std::string&
RoboCompWallDetector::WallDetectorPrx::ice_staticId()
{
    return RoboCompWallDetector::WallDetector::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompWallDetector_WallDetector_gotwalls_name = "gotwalls";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompWallDetector::upCast(::IceProxy::RoboCompWallDetector::WallDetector* p) { return p; }

void
::IceProxy::RoboCompWallDetector::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompWallDetector::WallDetector>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompWallDetector::WallDetector;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompWallDetector::WallDetector::_iceI_begin_gotwalls(const ::RoboCompWallDetector::WallList& iceP_lst, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompWallDetector_WallDetector_gotwalls_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompWallDetector_WallDetector_gotwalls_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_lst);
        result->endWriteParams();
        result->invoke(iceC_RoboCompWallDetector_WallDetector_gotwalls_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompWallDetector::WallDetector::end_gotwalls(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompWallDetector_WallDetector_gotwalls_name);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompWallDetector::WallDetector::_newInstance() const
{
    return new WallDetector;
}

const ::std::string&
IceProxy::RoboCompWallDetector::WallDetector::ice_staticId()
{
    return ::RoboCompWallDetector::WallDetector::ice_staticId();
}

RoboCompWallDetector::WallDetector::~WallDetector()
{
}

::Ice::Object* RoboCompWallDetector::upCast(::RoboCompWallDetector::WallDetector* p) { return p; }


namespace
{
const ::std::string iceC_RoboCompWallDetector_WallDetector_ids[2] =
{
    "::Ice::Object",
    "::RoboCompWallDetector::WallDetector"
};

}

bool
RoboCompWallDetector::WallDetector::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompWallDetector_WallDetector_ids, iceC_RoboCompWallDetector_WallDetector_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompWallDetector::WallDetector::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompWallDetector_WallDetector_ids[0], &iceC_RoboCompWallDetector_WallDetector_ids[2]);
}

const ::std::string&
RoboCompWallDetector::WallDetector::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompWallDetector::WallDetector::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompWallDetector::WallDetector";
    return typeId;
#else
    return iceC_RoboCompWallDetector_WallDetector_ids[1];
#endif
}

bool
RoboCompWallDetector::WallDetector::_iceD_gotwalls(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompWallDetector::WallList iceP_lst;
    istr->read(iceP_lst);
    inS.endReadParams();
    this->gotwalls(iceP_lst, current);
    inS.writeEmptyParams();
    return true;
}

namespace
{
const ::std::string iceC_RoboCompWallDetector_WallDetector_all[] =
{
    "gotwalls",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

bool
RoboCompWallDetector::WallDetector::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompWallDetector_WallDetector_all, iceC_RoboCompWallDetector_WallDetector_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompWallDetector_WallDetector_all)
    {
        case 0:
        {
            return _iceD_gotwalls(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompWallDetector::WallDetector::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::RoboCompWallDetector::WallDetector, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompWallDetector::WallDetector::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::RoboCompWallDetector::WallDetector, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
RoboCompWallDetector::_icePatchObjectPtr(WallDetectorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompWallDetector::WallDetectorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompWallDetector::WallDetector::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
