//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: GoalPublisher.ice
//  Source: GoalPublisher.idsl
//
//******************************************************************
#ifndef ROBOCOMPGOALPUBLISHER_ICE
#define ROBOCOMPGOALPUBLISHER_ICE
module RoboCompGoalPublisher
{
	struct GoalT
	{
		float x;
		float y;
	};
	interface GoalPublisher
	{
		void goalupdated (GoalT goal);
	};
};

#endif
