# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'configuration.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_confDialog(object):
    def setupUi(self, confDialog):
        if not confDialog.objectName():
            confDialog.setObjectName(u"confDialog")
        confDialog.resize(324, 482)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(confDialog.sizePolicy().hasHeightForWidth())
        confDialog.setSizePolicy(sizePolicy)
        self.label_nhumans = QLabel(confDialog)
        self.label_nhumans.setObjectName(u"label_nhumans")
        self.label_nhumans.setGeometry(QRect(90, 20, 141, 17))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_nhumans.setFont(font)
        self.nhumans_min = QSpinBox(confDialog)
        self.nhumans_min.setObjectName(u"nhumans_min")
        self.nhumans_min.setGeometry(QRect(50, 60, 81, 31))
        self.nhumans_max = QSpinBox(confDialog)
        self.nhumans_max.setObjectName(u"nhumans_max")
        self.nhumans_max.setGeometry(QRect(180, 60, 81, 31))
        self.nhumans_max.setValue(10)
        self.label_min_nhumans = QLabel(confDialog)
        self.label_min_nhumans.setObjectName(u"label_min_nhumans")
        self.label_min_nhumans.setGeometry(QRect(70, 40, 31, 17))
        self.label_max_nhumans = QLabel(confDialog)
        self.label_max_nhumans.setObjectName(u"label_max_nhumans")
        self.label_max_nhumans.setGeometry(QRect(200, 40, 31, 17))
        self.label_min_nwandhumans = QLabel(confDialog)
        self.label_min_nwandhumans.setObjectName(u"label_min_nwandhumans")
        self.label_min_nwandhumans.setGeometry(QRect(70, 130, 31, 17))
        self.label_max_nwandhumans = QLabel(confDialog)
        self.label_max_nwandhumans.setObjectName(u"label_max_nwandhumans")
        self.label_max_nwandhumans.setGeometry(QRect(200, 130, 31, 17))
        self.label_nwandhumans = QLabel(confDialog)
        self.label_nwandhumans.setObjectName(u"label_nwandhumans")
        self.label_nwandhumans.setGeometry(QRect(50, 110, 211, 17))
        self.label_nwandhumans.setFont(font)
        self.nwandhumans_min = QSpinBox(confDialog)
        self.nwandhumans_min.setObjectName(u"nwandhumans_min")
        self.nwandhumans_min.setGeometry(QRect(50, 150, 81, 31))
        self.nwandhumans_max = QSpinBox(confDialog)
        self.nwandhumans_max.setObjectName(u"nwandhumans_max")
        self.nwandhumans_max.setGeometry(QRect(180, 150, 81, 31))
        self.nwandhumans_max.setValue(8)
        self.label_nplants = QLabel(confDialog)
        self.label_nplants.setObjectName(u"label_nplants")
        self.label_nplants.setGeometry(QRect(90, 200, 131, 17))
        self.label_nplants.setFont(font)
        self.label_min_nplants = QLabel(confDialog)
        self.label_min_nplants.setObjectName(u"label_min_nplants")
        self.label_min_nplants.setGeometry(QRect(70, 220, 31, 17))
        self.label_max_nplants = QLabel(confDialog)
        self.label_max_nplants.setObjectName(u"label_max_nplants")
        self.label_max_nplants.setGeometry(QRect(200, 220, 31, 17))
        self.nplants_min = QSpinBox(confDialog)
        self.nplants_min.setObjectName(u"nplants_min")
        self.nplants_min.setGeometry(QRect(50, 240, 81, 31))
        self.nplants_min.setValue(0)
        self.nplants_max = QSpinBox(confDialog)
        self.nplants_max.setObjectName(u"nplants_max")
        self.nplants_max.setGeometry(QRect(180, 240, 81, 31))
        self.nplants_max.setValue(6)
        self.label_nplants_2 = QLabel(confDialog)
        self.label_nplants_2.setObjectName(u"label_nplants_2")
        self.label_nplants_2.setGeometry(QRect(90, 290, 131, 17))
        self.label_nplants_2.setFont(font)
        self.label_max_ntables = QLabel(confDialog)
        self.label_max_ntables.setObjectName(u"label_max_ntables")
        self.label_max_ntables.setGeometry(QRect(200, 310, 31, 17))
        self.ntables_min = QSpinBox(confDialog)
        self.ntables_min.setObjectName(u"ntables_min")
        self.ntables_min.setGeometry(QRect(50, 330, 81, 31))
        self.ntables_min.setValue(0)
        self.ntables_max = QSpinBox(confDialog)
        self.ntables_max.setObjectName(u"ntables_max")
        self.ntables_max.setGeometry(QRect(180, 330, 81, 31))
        self.ntables_max.setValue(5)
        self.label_min_ntables = QLabel(confDialog)
        self.label_min_ntables.setObjectName(u"label_min_ntables")
        self.label_min_ntables.setGeometry(QRect(70, 310, 31, 17))
        self.nrelations_min = QSpinBox(confDialog)
        self.nrelations_min.setObjectName(u"nrelations_min")
        self.nrelations_min.setGeometry(QRect(50, 420, 81, 31))
        self.label_min_nrelations = QLabel(confDialog)
        self.label_min_nrelations.setObjectName(u"label_min_nrelations")
        self.label_min_nrelations.setGeometry(QRect(70, 400, 31, 17))
        self.nrelations_max = QSpinBox(confDialog)
        self.nrelations_max.setObjectName(u"nrelations_max")
        self.nrelations_max.setGeometry(QRect(180, 420, 81, 31))
        self.nrelations_max.setValue(8)
        self.label_max_nrelations = QLabel(confDialog)
        self.label_max_nrelations.setObjectName(u"label_max_nrelations")
        self.label_max_nrelations.setGeometry(QRect(200, 400, 31, 17))
        self.label_nrelations = QLabel(confDialog)
        self.label_nrelations.setObjectName(u"label_nrelations")
        self.label_nrelations.setGeometry(QRect(80, 380, 151, 17))
        self.label_nrelations.setFont(font)

        self.retranslateUi(confDialog)

        QMetaObject.connectSlotsByName(confDialog)
    # setupUi

    def retranslateUi(self, confDialog):
        confDialog.setWindowTitle(QCoreApplication.translate("confDialog", u"Configuration", None))
        self.label_nhumans.setText(QCoreApplication.translate("confDialog", u"Number of humans", None))
        self.label_min_nhumans.setText(QCoreApplication.translate("confDialog", u"Min", None))
        self.label_max_nhumans.setText(QCoreApplication.translate("confDialog", u"Max", None))
        self.label_min_nwandhumans.setText(QCoreApplication.translate("confDialog", u"Min", None))
        self.label_max_nwandhumans.setText(QCoreApplication.translate("confDialog", u"Max", None))
        self.label_nwandhumans.setText(QCoreApplication.translate("confDialog", u"Number of wandering humans", None))
        self.label_nplants.setText(QCoreApplication.translate("confDialog", u"Number of plants", None))
        self.label_min_nplants.setText(QCoreApplication.translate("confDialog", u"Min", None))
        self.label_max_nplants.setText(QCoreApplication.translate("confDialog", u"Max", None))
        self.label_nplants_2.setText(QCoreApplication.translate("confDialog", u"Number of tables", None))
        self.label_max_ntables.setText(QCoreApplication.translate("confDialog", u"Max", None))
        self.label_min_ntables.setText(QCoreApplication.translate("confDialog", u"Min", None))
        self.label_min_nrelations.setText(QCoreApplication.translate("confDialog", u"Min", None))
        self.label_max_nrelations.setText(QCoreApplication.translate("confDialog", u"Max", None))
        self.label_nrelations.setText(QCoreApplication.translate("confDialog", u"Number of relations", None))
    # retranslateUi

