# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mainUI.ui'
#
# Created: Thu Jul 11 10:27:19 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_guiDlg(QtCore.QObject):
    def setupUi(self, guiDlg):
        guiDlg.setObjectName("guiDlg")
        guiDlg.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(guiDlg)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(800, 800))
        self.graphicsView.setMaximumSize(QtCore.QSize(2400, 2400))
        self.graphicsView.DragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        #self.graphicsView.ViewportUpdateMode(QtWidgets.QGraphicsView.SmartViewportUpdate)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setStyleSheet("color: rgba(0, 0, 0, 0.);")
        self.label5.setObjectName("label5")
        self.verticalLayout_3.addWidget(self.label5)
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setStyleSheet("color: rgba(0, 0, 0, 0.);")
        self.label4.setObjectName("label4")
        self.verticalLayout_3.addWidget(self.label4)
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setStyleSheet("color: rgba(0, 0, 0, 0.);")
        self.label3.setObjectName("label3")
        self.verticalLayout_3.addWidget(self.label3)
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setStyleSheet("color: rgba(0, 0, 0, 0.);")
        self.label2.setObjectName("label2")
        self.verticalLayout_3.addWidget(self.label2)
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setStyleSheet("color: rgba(0, 0, 0, 0.);")
        self.label1.setObjectName("label1")
        self.verticalLayout_3.addWidget(self.label1)
        self.label0 = QtWidgets.QLabel(self.centralwidget)
        self.label0.setStyleSheet("color: rgba(0, 0, 0, 0.);")
        self.label0.setObjectName("label0")
        self.verticalLayout_3.addWidget(self.label0)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.slider = QtWidgets.QSlider(self.centralwidget)
        self.slider.setMaximum(100)
        self.slider.setOrientation(QtCore.Qt.Vertical)
        self.slider.setObjectName("slider")
        self.horizontalLayout_3.addWidget(self.slider)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setObjectName("sendButton")
        self.verticalLayout_2.addWidget(self.sendButton)
        self.getButton = QtWidgets.QPushButton(self.centralwidget)
        self.getButton.setObjectName("getButton")
        self.verticalLayout_2.addWidget(self.getButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.estimateBox = QtWidgets.QCheckBox(self.centralwidget)
        self.estimateBox.setObjectName("estimateBox")
        self.verticalLayout_2.addWidget(self.estimateBox)
        self.estimateButton = QtWidgets.QPushButton(self.centralwidget)
        self.estimateButton.setObjectName("estimateButton")
        self.verticalLayout_2.addWidget(self.estimateButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        guiDlg.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(guiDlg)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 25))
        self.menubar.setObjectName("menubar")
        guiDlg.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(guiDlg)
        self.statusbar.setStyleSheet("font: 75 11pt \"Ubuntu\";")
        self.statusbar.setObjectName("statusbar")
        guiDlg.setStatusBar(self.statusbar)

        self.retranslateUi(guiDlg)
        QtCore.QMetaObject.connectSlotsByName(guiDlg)

    def retranslateUi(self, guiDlg):
        guiDlg.setWindowTitle(QtWidgets.QApplication.translate("guiDlg", "Social Navigation Dataset Generator", None, -1))
        self.label5.setText(QtWidgets.QApplication.translate("guiDlg", "perfect", None, -1))
        self.label4.setText(QtWidgets.QApplication.translate("guiDlg", "very good", None, -1))
        self.label3.setText(QtWidgets.QApplication.translate("guiDlg", "good", None, -1))
        self.label2.setText(QtWidgets.QApplication.translate("guiDlg", "acceptable", None, -1))
        self.label1.setText(QtWidgets.QApplication.translate("guiDlg", "undesirable", None, -1))
        self.label0.setText(QtWidgets.QApplication.translate("guiDlg", "unacceptable", None, -1))
        self.sendButton.setText(QtWidgets.QApplication.translate("guiDlg", "send\n"
"context\n"
"assessment", None, -1))
        self.getButton.setText(QtWidgets.QApplication.translate("guiDlg", "get new\n"
"sample", None, -1))
        self.estimateBox.setText(QtWidgets.QApplication.translate("guiDlg", "automatically\n"
"estimate", None, -1))
        self.estimateButton.setText(QtWidgets.QApplication.translate("guiDlg", "estimate", None, -1))
